# Generated by Django 4.2.8 on 2025-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_coupon_eventform_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='conditional_display',
            field=models.JSONField(blank=True, default=list, help_text='Rules for conditional display based on other fields', verbose_name='conditional display'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='default value'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='validations',
            field=models.JSONField(blank=True, default=dict, help_text='Validations like min, max, minLength, maxLength, pattern', verbose_name='validations'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='width',
            field=models.CharField(choices=[('full', 'Full width'), ('half', 'Half width'), ('third', 'Third width')], default='full', max_length=20, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('date', 'Date'), ('time', 'Time'), ('phone', 'Phone'), ('textarea', 'Textarea'), ('heading', 'Heading'), ('paragraph', 'Paragraph')], default='text', max_length=20, verbose_name='type'),
        ),
    ]
