# Generated by Django 4.2.8 on 2025-05-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_coupon_end_time_coupon_events_list_coupon_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
