# Generated by Django 4.2.8 on 2025-05-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('draft_complete', 'Borrador completo'), ('published', 'Publicado'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
