# Generated by Django 4.2.8 on 2025-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_description_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Leave empty for unlimited capacity', null=True, verbose_name='capacity'),
        ),
    ]
