# Generated by Django 4.2.8 on 2025-06-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_ticketcategory_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='eventcommunication',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='eventform',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='tickettier',
            name='tenant_id',
        ),
    ]
