# Generated by Django 4.2.8 on 2025-08-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_simplify_location'),
        ('events', '0010_migrate_to_unified_forms_system'),
    ]

    operations = [
    ]
