# Generated by Django 4.2.8 on 2025-08-18 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0009_alter_organizer_organizer_id'),
        ('events', '0011_merge_20250818_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Whether this event is free (only for simple pricing mode)', verbose_name='is free'),
        ),
        migrations.AddField(
            model_name='event',
            name='pricing_mode',
            field=models.CharField(choices=[('simple', 'Simple - Free with basic settings'), ('complex', 'Complex - Paid with tickets/categories')], default='simple', help_text='Simple: free events with basic settings. Complex: paid events with tickets/categories.', max_length=20, verbose_name='pricing mode'),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Whether attendees need approval to join (only for simple pricing mode)', verbose_name='requires approval'),
        ),
        migrations.AddField(
            model_name='event',
            name='simple_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Total capacity for simple events (null = unlimited)', null=True, verbose_name='simple capacity'),
        ),
        migrations.AddField(
            model_name='event',
            name='simple_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for simple paid events', max_digits=10, verbose_name='simple price'),
        ),
        migrations.CreateModel(
            name='SimpleBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('checked_in', models.BooleanField(default=False, verbose_name='checked in')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='check in time')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to='organizers.organizeruser', verbose_name='approved by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_bookings', to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'simple booking',
                'verbose_name_plural': 'simple bookings',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
