# Generated by Django 4.2.8 on 2025-08-18 23:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_ticketcategory_requires_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('released', models.BooleanField(default=False, verbose_name='released')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_holds', to='events.event', verbose_name='event')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='events.order', verbose_name='order')),
                ('ticket_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='events.tickettier', verbose_name='ticket tier')),
            ],
            options={
                'verbose_name': 'ticket hold',
                'verbose_name_plural': 'ticket holds',
                'indexes': [models.Index(fields=['ticket_tier', 'expires_at', 'released'], name='events_tick_ticket__176275_idx'), models.Index(fields=['event', 'expires_at', 'released'], name='events_tick_event_i_2ea61f_idx')],
            },
        ),
    ]
