# Generated by Django 4.2.8 on 2025-08-19 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_tickethold'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254, verbose_name='to email')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('template', models.CharField(blank=True, max_length=100, verbose_name='template')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='attempts')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, verbose_name='provider message id')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='events.order', verbose_name='order')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='events.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'email log',
                'verbose_name_plural': 'email logs',
                'indexes': [models.Index(fields=['to_email', 'status'], name='events_emai_to_emai_f4bf73_idx'), models.Index(fields=['order'], name='events_emai_order_i_0fffd1_idx'), models.Index(fields=['ticket'], name='events_emai_ticket__1f295a_idx')],
            },
        ),
    ]
