# Generated by Django 4.2.8 on 2025-08-19 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], help_text='Approval status for tickets that require approval', max_length=20, null=True, verbose_name='approval status'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='approved at'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved/rejected this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tickets', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='check_in_by',
            field=models.ForeignKey(blank=True, help_text='User (guard/staff) who performed the check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_tickets', to=settings.AUTH_USER_MODEL, verbose_name='checked in by'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='check_in_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked In'), ('no_show', 'No Show')], default='pending', help_text='Current check-in status of the ticket', max_length=20, verbose_name='check-in status'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if ticket was rejected', verbose_name='rejection reason'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='checked_in',
            field=models.BooleanField(default=False, help_text='Legacy field. Use check_in_status instead.', verbose_name='checked in (legacy)'),
        ),
    ]
