# Generated by Django 4.2.8 on 2025-08-20 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_enhance_ticket_model_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum purchase'),
        ),
    ]
