# Generated by Django 4.2.8 on 2025-08-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_allow_null_min_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
