# Generated by Django 4.2.8 on 2025-08-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_allow_null_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='event',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='events_list',
            field=models.JSONField(blank=True, help_text='null = Global (all events), [event_id] = Local (specific event)', null=True, verbose_name='applicable events'),
        ),
    ]
