# Generated by Django 4.2.8 on 2025-08-20 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0019_remove_legacy_event_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='content')),
                ('is_internal', models.BooleanField(default=True, help_text='Whether this note is internal (not visible to customer)', verbose_name='is internal')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='events.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket note',
                'verbose_name_plural': 'ticket notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
