# Generated by Django 4.2.8 on 2025-08-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_ticketnote'),
    ]

    operations = [
    ]
