# Generated by Django 4.2.8 on 2025-09-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_duplicate_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettier',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited capacity', null=True, verbose_name='capacity'),
        ),
    ]
