# Generated by Django 4.2.8 on 2025-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_tickettier_unlimited_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='start_time',
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['organizer', 'is_active'], name='events_coup_organiz_dd4efe_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'organizer'], name='events_coup_code_5c46f8_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date', 'end_date'], name='events_coup_start_d_9f9265_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['events_list'], name='coupon_events_gin'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('discount_value__gte', 0)), name='positive_discount_value'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('usage_count__gte', 0)), name='positive_usage_count'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('discount_type', 'percentage'), ('discount_value__lte', 100)), ('discount_type', 'fixed'), _connector='OR')), name='valid_percentage_discount'),
        ),
    ]
