# Generated by Django 4.2.8 on 2025-09-26 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_enterprise_coupon_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('released', models.BooleanField(default=False, verbose_name='released')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
            ],
            options={
                'verbose_name': 'coupon hold',
                'verbose_name_plural': 'coupon holds',
            },
        ),
        migrations.RemoveConstraint(
            model_name='coupon',
            name='positive_discount_value',
        ),
        migrations.RemoveConstraint(
            model_name='coupon',
            name='positive_usage_count',
        ),
        migrations.RemoveConstraint(
            model_name='coupon',
            name='valid_percentage_discount',
        ),
        migrations.RemoveIndex(
            model_name='coupon',
            name='events_coup_organiz_dd4efe_idx',
        ),
        migrations.RemoveIndex(
            model_name='coupon',
            name='events_coup_code_5c46f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='coupon',
            name='events_coup_start_d_9f9265_idx',
        ),
        migrations.RemoveIndex(
            model_name='coupon',
            name='coupon_events_gin',
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='sold',
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='available',
            field=models.PositiveIntegerField(default=0, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='capacity',
            field=models.PositiveIntegerField(default=1, verbose_name='capacity'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tickethold',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='events_tickethold_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='tickethold',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('created_at'))), name='events_tickethold_expires_after_creation'),
        ),
        migrations.AddConstraint(
            model_name='tickettier',
            constraint=models.CheckConstraint(check=models.Q(('available__gte', 0)), name='events_tickettier_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tickettier',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gte', 0)), name='events_tickettier_capacity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tickettier',
            constraint=models.CheckConstraint(check=models.Q(('max_per_order__gte', 1)), name='events_tickettier_max_per_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='tickettier',
            constraint=models.CheckConstraint(check=models.Q(('min_per_order__gte', 1)), name='events_tickettier_min_per_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='tickettier',
            constraint=models.CheckConstraint(check=models.Q(('max_per_order__gte', models.F('min_per_order'))), name='events_tickettier_max_gte_min_per_order'),
        ),
        migrations.AddField(
            model_name='couponhold',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='events.coupon', verbose_name='coupon'),
        ),
        migrations.AddField(
            model_name='couponhold',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_holds', to='events.order', verbose_name='order'),
        ),
        migrations.AddIndex(
            model_name='couponhold',
            index=models.Index(fields=['coupon', 'expires_at', 'released'], name='events_coup_coupon__fd4152_idx'),
        ),
        migrations.AddIndex(
            model_name='couponhold',
            index=models.Index(fields=['order', 'expires_at', 'released'], name='events_coup_order_i_8a05d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponhold',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('created_at'))), name='events_couponhold_expires_after_creation'),
        ),
    ]
