# Generated by Django 4.2.8 on 2025-09-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_add_email_validation_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettier',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited capacity', null=True, verbose_name='capacity'),
        ),
    ]
