# Generated by Django 4.2.8 on 2025-09-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_allow_null_capacity_in_ticket_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettier',
            name='available',
            field=models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited availability', null=True, verbose_name='available'),
        ),
    ]
