# Generated by Django 4.2.8 on 2025-10-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_allow_null_available_in_ticket_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the event was soft deleted', null=True, verbose_name='deleted at'),
        ),
    ]
