# Generated by Django 4.2.8 on 2025-10-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_migrate_service_fee_to_rates'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tickettier',
            name='events_tickettier_available_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='tickettier',
            name='events_tickettier_capacity_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='tickettier',
            name='events_tickettier_max_per_order_positive',
        ),
        migrations.RemoveConstraint(
            model_name='tickettier',
            name='events_tickettier_min_per_order_positive',
        ),
        migrations.RemoveConstraint(
            model_name='tickettier',
            name='events_tickettier_max_gte_min_per_order',
        ),
    ]
