# Generated by Django 4.2.8 on 2025-10-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_remove_tickettier_events_tickettier_available_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethold',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom price per ticket for Pay-What-You-Want tickets', max_digits=10, null=True, verbose_name='custom price'),
        ),
    ]
