# Generated by Django 4.2.8 on 2025-10-09 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_add_custom_price_to_tickethold'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHolderReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder_index', models.PositiveIntegerField(help_text='Index of this holder within the tier (0, 1, 2, etc.)', verbose_name='holder index')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('form_data', models.JSONField(blank=True, default=dict, help_text='Additional form data collected for this ticket holder', verbose_name='form data')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_holder_reservations', to='events.order', verbose_name='order')),
                ('ticket_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tickettier', verbose_name='ticket tier')),
            ],
            options={
                'verbose_name': 'Ticket Holder Reservation',
                'verbose_name_plural': 'Ticket Holder Reservations',
                'indexes': [models.Index(fields=['order', 'ticket_tier'], name='events_tick_order_i_30216c_idx'), models.Index(fields=['created_at'], name='events_tick_created_995733_idx')],
                'unique_together': {('order', 'ticket_tier', 'holder_index')},
            },
        ),
    ]
