# Generated by Django 4.2.8 on 2025-10-18 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0035_add_ticket_holder_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Anonymous session identifier', max_length=40, verbose_name='session ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='referer')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM campaign')),
                ('utm_term', models.CharField(blank=True, max_length=100, verbose_name='UTM term')),
                ('utm_content', models.CharField(blank=True, max_length=100, verbose_name='UTM content')),
                ('view_source', models.CharField(choices=[('web', 'Website'), ('mobile_app', 'Mobile App'), ('social_media', 'Social Media'), ('direct', 'Direct Link'), ('search', 'Search Engine'), ('email', 'Email Campaign'), ('partner', 'Partner Site'), ('qr_code', 'QR Code'), ('other', 'Other')], default='web', max_length=20, verbose_name='view source')),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='device type')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('time_on_page', models.PositiveIntegerField(blank=True, help_text='Time spent viewing the event page', null=True, verbose_name='time on page (seconds)')),
                ('converted_to_purchase', models.BooleanField(default=False, help_text='Whether this view led to a ticket purchase', verbose_name='converted to purchase')),
                ('conversion_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_views', to='events.order', verbose_name='conversion order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='events.event', verbose_name='event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_views', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'event view',
                'verbose_name_plural': 'event views',
                'indexes': [models.Index(fields=['event', 'created_at'], name='events_even_event_i_550a40_idx'), models.Index(fields=['session_id', 'created_at'], name='events_even_session_2c1475_idx'), models.Index(fields=['ip_address', 'created_at'], name='events_even_ip_addr_d537cd_idx'), models.Index(fields=['view_source', 'device_type'], name='events_even_view_so_d60117_idx'), models.Index(fields=['converted_to_purchase'], name='events_even_convert_bac6a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventPerformanceMetrics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='total views')),
                ('unique_views', models.PositiveIntegerField(default=0, verbose_name='unique views')),
                ('avg_time_on_page', models.FloatField(default=0, verbose_name='average time on page')),
                ('total_conversions', models.PositiveIntegerField(default=0, verbose_name='total conversions')),
                ('conversion_rate', models.FloatField(default=0, verbose_name='conversion rate')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total revenue')),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='average order value')),
                ('web_views', models.PositiveIntegerField(default=0, verbose_name='web views')),
                ('mobile_views', models.PositiveIntegerField(default=0, verbose_name='mobile views')),
                ('social_media_views', models.PositiveIntegerField(default=0, verbose_name='social media views')),
                ('direct_views', models.PositiveIntegerField(default=0, verbose_name='direct views')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'event performance metrics',
                'verbose_name_plural': 'event performance metrics',
                'indexes': [models.Index(fields=['event', 'date'], name='events_even_event_i_623d43_idx'), models.Index(fields=['date'], name='events_even_date_4fb98d_idx')],
                'unique_together': {('event', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=40, verbose_name='session ID')),
                ('stage', models.CharField(choices=[('view', 'Event View'), ('ticket_selection', 'Ticket Selection'), ('checkout_start', 'Checkout Started'), ('payment_info', 'Payment Info Entered'), ('purchase_complete', 'Purchase Completed'), ('abandoned', 'Abandoned')], max_length=20, verbose_name='funnel stage')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantity')),
                ('time_from_view', models.PositiveIntegerField(blank=True, null=True, verbose_name='time from initial view (seconds)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_stages', to='events.event', verbose_name='event')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.order', verbose_name='completed order')),
                ('ticket_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.tickettier', verbose_name='ticket tier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'conversion funnel stage',
                'verbose_name_plural': 'conversion funnel stages',
                'indexes': [models.Index(fields=['event', 'stage', 'created_at'], name='events_conv_event_i_e6d1f9_idx'), models.Index(fields=['session_id', 'created_at'], name='events_conv_session_0e667d_idx')],
            },
        ),
    ]
