# Generated by Django 4.2.8 on 2025-10-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_eventview_eventperformancemetrics_conversionfunnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Date and time when this ticket becomes available for purchase. Leave empty for immediate availability.', null=True, verbose_name='available from'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this ticket tier is currently active and can be purchased', verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum total quantity that can be sold for this tier (across all orders). Leave empty for unlimited.', null=True, verbose_name='max quantity'),
        ),
    ]
