# Generated by Django 4.2.8 on 2025-12-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_platform_flow_monitoring'),
        ('events', '0037_add_ticket_tier_availability_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flow',
            field=models.ForeignKey(blank=True, help_text='Platform flow that created this order (for tracking and debugging)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.platformflow', verbose_name='platform flow'),
        ),
    ]
