# Generated by Django 4.2.8 on 2025-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_add_raffle_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.TextField(blank=True, help_text='Base64-encoded QR code image for instant email delivery', verbose_name='QR code'),
        ),
    ]
