# Generated by Django 4.2.8 on 2025-12-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_add_qr_code_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, help_text='Secure token for public access to order tickets (generated automatically)', max_length=64, null=True, unique=True, verbose_name='access token'),
        ),
    ]
