# Generated by Django 4.2.8 on 2025-12-09 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_add_access_token_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_fee_effective',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Effective platform commission after proportional discount (integer for CLP)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='effective service fee'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_effective',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Effective organizer revenue after proportional discount (integer for CLP)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='effective subtotal'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtotal_effective',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Effective subtotal: (unit_price_effective + unit_service_fee_effective) × quantity', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='effective subtotal'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_effective',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Effective unit price after proportional discount (integer for CLP)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='effective unit price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_service_fee_effective',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Effective unit service fee after proportional discount (integer for CLP)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='effective unit service fee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total discount applied (from coupon)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service fee original (before discount) - platform commission', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='service fee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal original (before discount) - organizer revenue', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final amount paid by customer (after discount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Original subtotal: (unit_price + unit_service_fee) × quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Original unit price (before discount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original unit service fee (before discount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit service fee'),
        ),
    ]
