# Generated by Django 4.2.8 on 2025-12-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_booking_horizon_days_and_more'),
        ('events', '0042_add_effective_revenue_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='experience_reservation',
            field=models.ForeignKey(blank=True, help_text='Linked experience reservation for experience orders. Null for event orders.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='experiences.experiencereservation', verbose_name='experience reservation'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_kind',
            field=models.CharField(choices=[('event', 'Event Order'), ('experience', 'Experience Order')], default='event', help_text='Domain this order belongs to: event tickets or experiences.', max_length=20, verbose_name='order kind'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Linked event for event orders. Null for experience orders.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.event', verbose_name='event'),
        ),
    ]
