# Generated by Django 4.2.8 on 2026-01-06 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0043_order_experience_reservation_order_order_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='complimentary_tier_for_event',
            field=models.OneToOneField(blank=True, help_text='One complimentary tier per event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_tier', to='events.event', verbose_name='complimentary tier for event'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='is_complimentary',
            field=models.BooleanField(default=False, help_text="Marks this tier as special for complimentary tickets (doesn't affect inventory)", verbose_name='is complimentary'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, help_text='Email is optional for complimentary tickets without email', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.CreateModel(
            name='ComplimentaryTicketInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('email', models.EmailField(blank=True, help_text='Email may be empty for invitations', max_length=254, verbose_name='email')),
                ('max_tickets', models.PositiveIntegerField(default=1, help_text='Maximum number of tickets allowed (1 or 2)', verbose_name='max tickets')),
                ('tickets_per_invitation', models.PositiveIntegerField(default=1, help_text='Number of tickets configured when invitation was created', verbose_name='tickets per invitation')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de canje'), ('redeemed', 'Canjeada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='status')),
                ('public_token', models.CharField(db_index=True, help_text='Secure token for public redemption URL', max_length=64, unique=True, verbose_name='public token')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='redeemed at')),
                ('redeemed_by_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='redeemed by email')),
                ('created_by', models.ForeignKey(blank=True, help_text='Organizer who created this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_complimentary_invitations', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_invitations', to='events.event', verbose_name='event')),
                ('order', models.ForeignKey(blank=True, help_text='Order created when this invitation was redeemed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complimentary_invitations', to='events.order', verbose_name='order')),
                ('ticket_tier', models.ForeignKey(help_text='Complimentary ticket tier for this event', on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_invitations', to='events.tickettier', verbose_name='ticket tier')),
            ],
            options={
                'verbose_name': 'complimentary ticket invitation',
                'verbose_name_plural': 'complimentary ticket invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['public_token'], name='events_comp_public__6b1d72_idx'), models.Index(fields=['event', 'status'], name='events_comp_event_i_343500_idx'), models.Index(fields=['status', '-created_at'], name='events_comp_status_523dc2_idx')],
            },
        ),
    ]
