# Generated by Django 4.2.8 on 2026-02-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0014_add_managed_operator_slug'),
        ('events', '0045_order_accommodation_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='experience_reservation',
            field=models.ForeignKey(blank=True, help_text='Linked experience reservation for experience orders. Null for event/acc orders.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='experiences.experiencereservation', verbose_name='experience reservation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_kind',
            field=models.CharField(choices=[('event', 'Event Order'), ('experience', 'Experience Order'), ('accommodation', 'Accommodation Order')], default='event', help_text='Domain this order belongs to: event tickets or experiences.', max_length=20, verbose_name='order kind'),
        ),
    ]
