# Generated by Django 4.2.8 on 2026-02-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_order_car_rental_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_kind',
            field=models.CharField(choices=[('event', 'Event Order'), ('experience', 'Experience Order'), ('accommodation', 'Accommodation Order'), ('car_rental', 'Car Rental Order')], default='event', help_text='Domain this order belongs to: event tickets or experiences.', max_length=20, verbose_name='order kind'),
        ),
    ]
