# Generated by Django 4.2.8 on 2026-03-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_order_exclude_from_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='booking date'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancellation date'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_policy_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='cancellation policy snapshot'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='cancellation reason'),
        ),
        migrations.AddField(
            model_name='order',
            name='commercial_policy_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='commercial policy snapshot'),
        ),
        migrations.AddField(
            model_name='order',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completion date'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='payment date'),
        ),
        migrations.AddField(
            model_name='order',
            name='posting_date',
            field=models.DateField(blank=True, null=True, verbose_name='posting date'),
        ),
        migrations.AddField(
            model_name='order',
            name='processor_fee_loss_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='processor fee loss amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_responsibility',
            field=models.CharField(blank=True, choices=[('tuki', 'Tuki'), ('organizer', 'Organizer')], max_length=20, verbose_name='refund responsibility'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='service date'),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='settlement date'),
        ),
    ]
