"""URL Configuration for Super Admin API."""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from apps.landing_destinations.views import LandingDestinationViewSet
from .views.rental_hubs import RentalHubViewSet
from .views.hotels import HotelViewSet, create_hotel_from_json, update_hotel_from_json
from .views import (
    TravelGuideListView,
    TravelGuideDetailView,
    TravelGuideCreateView,
    create_travel_guide_from_json,
    TravelGuideCreateHiddenInstanceView,
    TravelGuideDeleteHiddenInstanceView,
    SuperAdminUserViewSet,
    CountryViewSet,
    platform_status,
    platform_uptime_report,
    deploys_list,
    email_health_check,
    SuperAdminAccommodationListView,
    SuperAdminAccommodationDetailView,
    SuperAdminAccommodationGalleryUpdateView,
    create_accommodation_from_json,
    update_accommodation_from_json,
    bulk_upload_gallery_zip,
    accommodation_blocked_dates,
    SuperAdminCarRentalCompanyListView,
    SuperAdminCarRentalCompanyDetailView,
    SuperAdminCarListView,
    SuperAdminCarDetailView,
    SuperAdminCarGalleryUpdateView,
    create_car_rental_company_from_json,
    create_car_from_json,
    schema_for_entity,
    create_destination_from_json,
    ErasmusLeadsView,
    ErasmusLeadsExportView,
    ErasmusLeadDetailView,
    ErasmusLeadWelcomeMessageView,
    ErasmusWelcomeMessageTemplatesView,
    ErasmusDashboardView,
    create_erasmus_leads_from_json,
    create_erasmus_timeline_from_json,
    create_erasmus_activity_from_json,
    link_experience_to_erasmus_activity,
    ErasmusActivityListView,
    ErasmusActivityDetailView,
    ErasmusActivityInstanceListCreateView,
    ErasmusActivityInstanceDetailView,
    ErasmusActivityInstanceInscriptionsView,
    ErasmusActivityPublicLinkView,
    ErasmusActivityReviewsListView,
    ErasmusActivityReviewDeleteView,
    erasmus_activity_instances_bulk_from_json,
    ErasmusTrackingLinkViewSet,
    ErasmusExtraFieldViewSet,
    ErasmusActivityExtraFieldViewSet,
    ErasmusDestinationGuideViewSet,
    ErasmusLocalPartnerViewSet,
    ErasmusWhatsAppGroupViewSet,
    erasmus_whatsapp_groups_bulk_from_json,
    erasmus_whatsapp_group_fetch_image,
    ErasmusRumiNotificationConfigView,
    erasmus_inscription_payment_exclude_from_revenue,
    erasmus_slides_list,
    erasmus_slides_assign,
    erasmus_slides_create,
    erasmus_slides_delete,
    erasmus_slides_reorder,
    ContestListView,
    ContestDetailView,
    ContestCreateView,
    ContestSlidesView,
    ContestSlideAssignView,
    ContestSlideDeleteView,
    ContestSlidesReorderView,
    ContestExtraFieldViewSet,
    ContestParticipantsView,
    ContestParticipantsExportView,
    hero_vitrina_list,
    hero_vitrina_add,
    hero_vitrina_remove,
    hero_vitrina_reorder,
    erasmus_registro_background_list,
    erasmus_registro_background_create,
    erasmus_registro_background_delete,
    erasmus_registro_background_assign,
    erasmus_registro_background_reorder,
    auth_background_list,
    auth_background_create,
    auth_background_delete,
    auth_background_assign,
    auth_background_reorder,
    superadmin_stats,
    sales_analytics,
    organizer_sales,
    events_analytics,
    dashboard_time_series, 
    update_organizer_template,
    update_organizer_modules,
    update_organizer_service_fee,
    impersonate_organizer,
    update_event_service_fee,
    get_event_detail,
    update_ticket_tier_service_fee,
    # 🚀 ENTERPRISE: Platform Flow Monitoring
    ticket_delivery_funnel,
    ticket_delivery_issues,
    all_flows,
    flow_detail,
    resend_order_email,
    bulk_resend_emails,
    celery_tasks_list,
    historical_conversion_rates,
    events_list,
    # 🚀 ENTERPRISE: Revenue Migration
    revenue_migration_status,
    migrate_revenue_data,
    # Finances
    pending_payouts,
    create_payout,
    export_payouts,
    bank_options,
    finance_sync,
    finance_overview,
    finance_payees,
    finance_payee_detail,
    finance_payouts,
    finance_create_paid_payout,
    finance_update_payout,
    finance_batches,
    finance_batch_export,
    finance_batch_mark_paid,
    finance_export_files,
    finance_platform_settings,
    finance_payout_attachment_upload,
    finance_audit,
)
from .views.finance_revenue import (
    finance_external_revenue_import,
    finance_external_revenue_list,
    finance_external_revenue_detail,
    finance_external_revenue_exclude,
    finance_external_revenue_reverse,
    finance_revenue_insights,
    finance_documents,
)
from .views.finance_settlements import (
    finance_settlements_list,
    finance_settlements_calculate,
    finance_settlement_post,
    finance_settlement_void,
    finance_third_party_funds,
)
from .views.finance_vendors import (
    finance_vendors,
    finance_vendor_detail,
    finance_vendor_bills,
    finance_vendor_bills_create_from_json,
    finance_vendor_bill_post,
    finance_vendor_bill_void,
    finance_vendor_payments,
    finance_vendor_aging,
    finance_expense_categories,
    finance_cost_centers,
    finance_tax_treatments,
)
from .views.finance_treasury import (
    finance_bank_accounts,
    finance_bank_account_detail,
    finance_bank_reconciliations,
    finance_bank_statement_line_classify,
    finance_bank_statement_line_ignore,
    finance_bank_statement_line_unclassify,
    finance_bank_statement_lines,
    finance_bank_statement_matchable_payouts,
    finance_bank_statement_matchable_settlements,
    finance_bank_statement_matchable_vendor_payments,
    finance_bank_statement_summary,
    finance_bank_statements_import,
    finance_processor_settlements,
    finance_treasury_position,
)
from .views.finance_ledger import (
    finance_ledger_accounts,
    finance_ledger_journal,
    finance_ledger_journal_detail,
)
from .views.finance_reports import (
    finance_report_balance_sheet,
    finance_report_income_statement,
    finance_report_cash_flow,
)
from .views.finance_cancellations import (
    finance_cancel_order,
    finance_payout_clawback,
)
# Hack: re-open the previous import block to keep existing code working
from .views import (
    # Órdenes y pagos (estado, intentos, errores, sandbox, papelera)
    orders_list,
    order_detail,
    order_exclude_from_revenue,
    order_soft_delete,
    order_restore,
    order_permanent_delete,
    # 🚀 ENTERPRISE: JSON Experience Creation
    create_experience_from_json,
    update_experience_commission,
    superadmin_experience_detail,
    experience_landing_destinations,
    superadmin_experience_instances,
    superadmin_experience_instances_block_by_date,
    superadmin_experience_instances_unblock_by_date,
    superadmin_experience_regenerate_instances,
    superadmin_experience_instance_bookings,
    superadmin_experience_instance_cancel_and_notify,
    superadmin_experience_bookings_by_date,
    creators_landing_slots_list,
    creators_landing_slots_assign,
    SuperAdminCreatorsListView,
)
from .whatsapp_views import (
    whatsapp_status,
    whatsapp_disconnect,
    whatsapp_qr,
    whatsapp_request_new_qr,
    whatsapp_profile_picture,
    whatsapp_reservations,
    whatsapp_operators,
    whatsapp_bind_experience_operator,
    whatsapp_messages,
    whatsapp_mark_message_reservation,
    whatsapp_chats,
    whatsapp_chat_info,
    whatsapp_update_chat,
    whatsapp_mark_chat_read,
    whatsapp_assign_chat_operator,
    whatsapp_sync_chats,
    whatsapp_send_message,
    whatsapp_groups,
    whatsapp_group_info,
    whatsapp_assign_group_operator,
    whatsapp_group_outreach,
    whatsapp_outreach_run_now,
    whatsapp_group_outreach_send_one,
    whatsapp_experiences,
    whatsapp_experience_group,
    whatsapp_accommodations,
    whatsapp_accommodation_group,
    whatsapp_hotels,
    whatsapp_hotel_group,
    whatsapp_rental_hubs,
    whatsapp_rental_hub_group,
    whatsapp_reservation_messages,
    whatsapp_experience_reservation_messages,
    whatsapp_accommodation_reservation_messages,
    whatsapp_hotel_reservation_messages,
    whatsapp_rental_hub_reservation_messages,
    whatsapp_operator_detail,
    whatsapp_operator_default_group,
)

# Create router
router = DefaultRouter()
router.register(r'users', SuperAdminUserViewSet, basename='superadmin-users')
router.register(r'countries', CountryViewSet, basename='country')
router.register(r'destinations', LandingDestinationViewSet, basename='superadmin-destinations')
router.register(r'rental-hubs', RentalHubViewSet, basename='superadmin-rental-hubs')
router.register(r'hotels', HotelViewSet, basename='superadmin-hotels')

urlpatterns = [
    # Rutas específicas ANTES del router para que no sean capturadas por <resource>/<pk>/
    path('destinations/create-from-json/', create_destination_from_json, name='create-destination-from-json'),
    path('travel-guides/', TravelGuideListView.as_view(), name='superadmin-travel-guides-list'),
    path('travel-guides/create/', TravelGuideCreateView.as_view(), name='superadmin-travel-guides-create'),
    path('travel-guides/create-from-json/', create_travel_guide_from_json, name='superadmin-travel-guides-create-from-json'),
    path('travel-guides/<uuid:guide_id>/', TravelGuideDetailView.as_view(), name='superadmin-travel-guides-detail'),
    path('travel-guides/<uuid:guide_id>/experience-block/<str:block_key>/guide-instances/', TravelGuideCreateHiddenInstanceView.as_view(), name='superadmin-travel-guides-create-hidden-instance'),
    path('travel-guides/<uuid:guide_id>/guide-instances/<uuid:instance_id>/', TravelGuideDeleteHiddenInstanceView.as_view(), name='superadmin-travel-guides-delete-hidden-instance'),
    path('hotels/create-from-json/', create_hotel_from_json, name='create-hotel-from-json'),
    path('hotels/<uuid:hotel_id>/from-json/', update_hotel_from_json, name='update-hotel-from-json'),
    path('', include(router.urls)),
    path('platform-status/', platform_status, name='superadmin-platform-status'),
    path('platform-uptime-report/', platform_uptime_report, name='superadmin-platform-uptime-report'),
    path('email-health-check/', email_health_check, name='superadmin-email-health-check'),
    path('deploys/', deploys_list, name='superadmin-deploys-list'),
    path('stats/', superadmin_stats, name='superadmin-stats'),
    path('sales-analytics/', sales_analytics, name='sales-analytics'),
    path('dashboard-time-series/', dashboard_time_series, name='dashboard-time-series'),
    path('organizer-sales/', organizer_sales, name='organizer-sales'),
    path('events-analytics/', events_analytics, name='events-analytics'),
    path('organizers/<str:organizer_id>/template/', update_organizer_template, name='update-organizer-template'),
    path('organizers/<str:organizer_id>/modules/', update_organizer_modules, name='update-organizer-modules'),
    path('organizers/<str:organizer_id>/service-fee/', update_organizer_service_fee, name='update-organizer-service-fee'),
    path('organizers/<str:organizer_id>/impersonate/', impersonate_organizer, name='impersonate-organizer'),
    path('events/<str:event_id>/ticket-tiers/<str:tier_id>/service-fee/', update_ticket_tier_service_fee, name='update-ticket-tier-service-fee'),
    path('events/<str:event_id>/', get_event_detail, name='superadmin-event-detail'),
    path('events/<str:event_id>/service-fee/', update_event_service_fee, name='update-event-service-fee'),
    
    # 🚀 ENTERPRISE: Platform Flow Monitoring Endpoints
    path('ticket-delivery-funnel/', ticket_delivery_funnel, name='ticket-delivery-funnel'),
    path('ticket-delivery-issues/', ticket_delivery_issues, name='ticket-delivery-issues'),
    path('events-list/', events_list, name='events-list'),
    path('flows/', all_flows, name='all-flows'),
    # IMPORTANT: Specific paths must come before generic ones
    path('flows/bulk-resend-emails/', bulk_resend_emails, name='bulk-resend-emails'),
    path('flows/<str:flow_id>/resend-email/', resend_order_email, name='resend-order-email'),
    path('flows/<str:flow_id>/', flow_detail, name='flow-detail'),
    path('celery-tasks/', celery_tasks_list, name='celery-tasks-list'),
    path('historical-conversion-rates/', historical_conversion_rates, name='historical-conversion-rates'),
    
    # 🚀 ENTERPRISE: Revenue Migration Endpoints
    path('revenue-migration/status/', revenue_migration_status, name='revenue-migration-status'),
    path('revenue-migration/migrate/', migrate_revenue_data, name='migrate-revenue-data'),
    path('pending-payouts/', pending_payouts, name='pending-payouts'),
    path('pending-payouts/export/', export_payouts, name='export-payouts'),
    path('payouts/', create_payout, name='create-payout'),
    path('bank-options/', bank_options, name='bank-options'),
    path('finance/sync/', finance_sync, name='finance-sync'),
    path('finance/overview/', finance_overview, name='finance-overview'),
    path('finance/payees/', finance_payees, name='finance-payees'),
    path('finance/payees/<uuid:payee_id>/', finance_payee_detail, name='finance-payee-detail'),
    path('finance/payouts/', finance_payouts, name='finance-payouts'),
    path('finance/payouts/create-paid/', finance_create_paid_payout, name='finance-create-paid-payout'),
    path('finance/payouts/<uuid:payout_id>/', finance_update_payout, name='finance-update-payout'),
    path('finance/payouts/<uuid:payout_id>/attachments/', finance_payout_attachment_upload, name='finance-payout-attachment-upload'),
    path('finance/batches/', finance_batches, name='finance-batches'),
    path('finance/batches/<uuid:batch_id>/export/', finance_batch_export, name='finance-batch-export'),
    path('finance/batches/<uuid:batch_id>/mark-paid/', finance_batch_mark_paid, name='finance-batch-mark-paid'),
    path('finance/export-files/', finance_export_files, name='finance-export-files'),
    path('finance/platform-settings/', finance_platform_settings, name='finance-platform-settings'),
    path('finance/audit/', finance_audit, name='finance-audit'),
    # External revenue
    path('finance/external-revenue/import/', finance_external_revenue_import, name='finance-external-revenue-import'),
    path('finance/external-revenue/', finance_external_revenue_list, name='finance-external-revenue-list'),
    path('finance/external-revenue/<uuid:record_id>/', finance_external_revenue_detail, name='finance-external-revenue-detail'),
    path('finance/external-revenue/<uuid:record_id>/exclude_from_revenue/', finance_external_revenue_exclude, name='finance-external-revenue-exclude'),
    path('finance/external-revenue/<uuid:record_id>/reverse/', finance_external_revenue_reverse, name='finance-external-revenue-reverse'),
    path('finance/revenue-insights/', finance_revenue_insights, name='finance-revenue-insights'),
    path('finance/documents/', finance_documents, name='finance-documents'),
    # Settlements
    path('finance/settlements/', finance_settlements_list, name='finance-settlements-list'),
    path('finance/settlements/calculate/', finance_settlements_calculate, name='finance-settlements-calculate'),
    path('finance/settlements/<uuid:settlement_id>/post/', finance_settlement_post, name='finance-settlement-post'),
    path('finance/settlements/<uuid:settlement_id>/void/', finance_settlement_void, name='finance-settlement-void'),
    path('finance/third-party-funds/', finance_third_party_funds, name='finance-third-party-funds'),
    # Vendors & expenses
    path('finance/vendors/', finance_vendors, name='finance-vendors'),
    path('finance/vendors/<uuid:vendor_id>/', finance_vendor_detail, name='finance-vendor-detail'),
    path('finance/vendor-bills/create-from-json/', finance_vendor_bills_create_from_json, name='finance-vendor-bills-create-from-json'),
    path('finance/vendor-bills/', finance_vendor_bills, name='finance-vendor-bills'),
    path('finance/vendor-bills/<uuid:bill_id>/post/', finance_vendor_bill_post, name='finance-vendor-bill-post'),
    path('finance/vendor-bills/<uuid:bill_id>/void/', finance_vendor_bill_void, name='finance-vendor-bill-void'),
    path('finance/vendor-payments/', finance_vendor_payments, name='finance-vendor-payments'),
    path('finance/vendor-aging/', finance_vendor_aging, name='finance-vendor-aging'),
    path('finance/expense-categories/', finance_expense_categories, name='finance-expense-categories'),
    path('finance/cost-centers/', finance_cost_centers, name='finance-cost-centers'),
    path('finance/tax-treatments/', finance_tax_treatments, name='finance-tax-treatments'),
    # Treasury
    path('finance/bank-accounts/', finance_bank_accounts, name='finance-bank-accounts'),
    path('finance/bank-accounts/<uuid:account_id>/', finance_bank_account_detail, name='finance-bank-account-detail'),
    path('finance/bank-statements/import/', finance_bank_statements_import, name='finance-bank-statements-import'),
    path('finance/bank-statements/lines/', finance_bank_statement_lines, name='finance-bank-statement-lines'),
    path('finance/bank-statements/lines/<uuid:line_id>/classify/', finance_bank_statement_line_classify, name='finance-bank-statement-line-classify'),
    path('finance/bank-statements/lines/<uuid:line_id>/unclassify/', finance_bank_statement_line_unclassify, name='finance-bank-statement-line-unclassify'),
    path('finance/bank-statements/lines/<uuid:line_id>/ignore/', finance_bank_statement_line_ignore, name='finance-bank-statement-line-ignore'),
    path('finance/bank-statements/matchable-payouts/', finance_bank_statement_matchable_payouts, name='finance-bank-statement-matchable-payouts'),
    path('finance/bank-statements/matchable-vendor-payments/', finance_bank_statement_matchable_vendor_payments, name='finance-bank-statement-matchable-vendor-payments'),
    path('finance/bank-statements/matchable-settlements/', finance_bank_statement_matchable_settlements, name='finance-bank-statement-matchable-settlements'),
    path('finance/bank-statements/summary/<uuid:account_id>/', finance_bank_statement_summary, name='finance-bank-statement-summary'),
    path('finance/processor-settlements/', finance_processor_settlements, name='finance-processor-settlements'),
    path('finance/treasury-position/', finance_treasury_position, name='finance-treasury-position'),
    path('finance/bank-reconciliations/', finance_bank_reconciliations, name='finance-bank-reconciliations'),
    # Ledger
    path('finance/ledger/accounts/', finance_ledger_accounts, name='finance-ledger-accounts'),
    path('finance/ledger/journal/', finance_ledger_journal, name='finance-ledger-journal'),
    path('finance/ledger/journal/<uuid:entry_id>/', finance_ledger_journal_detail, name='finance-ledger-journal-detail'),
    # Financial reports
    path('finance/reports/balance-sheet/', finance_report_balance_sheet, name='finance-report-balance-sheet'),
    path('finance/reports/income-statement/', finance_report_income_statement, name='finance-report-income-statement'),
    path('finance/reports/cash-flow/', finance_report_cash_flow, name='finance-report-cash-flow'),
    # Cancellations & refunds
    path('finance/orders/<uuid:order_id>/cancel/', finance_cancel_order, name='finance-cancel-order'),
    path('finance/payouts/<uuid:payout_id>/clawback/', finance_payout_clawback, name='finance-payout-clawback'),
    path('orders/', orders_list, name='superadmin-orders-list'),
    path('orders/<uuid:order_id>/', order_detail, name='superadmin-order-detail'),
    path('orders/<uuid:order_id>/exclude_from_revenue/', order_exclude_from_revenue, name='superadmin-order-exclude-from-revenue'),
    path('orders/<uuid:order_id>/soft_delete/', order_soft_delete, name='superadmin-order-soft-delete'),
    path('orders/<uuid:order_id>/restore/', order_restore, name='superadmin-order-restore'),
    path('orders/<uuid:order_id>/permanent_delete/', order_permanent_delete, name='superadmin-order-permanent-delete'),
    # 🚀 ENTERPRISE: WhatsApp Integration Endpoints
    path('whatsapp/status/', whatsapp_status, name='whatsapp-status'),
    path('whatsapp/disconnect/', whatsapp_disconnect, name='whatsapp-disconnect'),
    path('whatsapp/qr/', whatsapp_qr, name='whatsapp-qr'),
    path('whatsapp/request-new-qr/', whatsapp_request_new_qr, name='whatsapp-request-new-qr'),
    path('whatsapp/reservations/', whatsapp_reservations, name='whatsapp-reservations'),
    path('whatsapp/operators/', whatsapp_operators, name='whatsapp-operators'),
    path('whatsapp/bind-experience-operator/', whatsapp_bind_experience_operator, name='whatsapp-bind-experience-operator'),
    path('whatsapp/messages/', whatsapp_messages, name='whatsapp-messages'),
    path('whatsapp/messages/<str:message_id>/mark-reservation/', whatsapp_mark_message_reservation, name='whatsapp-mark-message-reservation'),
    path('whatsapp/chats/', whatsapp_chats, name='whatsapp-chats'),
    path('whatsapp/profile-picture/<str:chat_id>/', whatsapp_profile_picture, name='whatsapp-profile-picture'),
    path('whatsapp/chats/sync/', whatsapp_sync_chats, name='whatsapp-sync-chats'),
    path('whatsapp/chats/<str:chat_id>/', whatsapp_chat_info, name='whatsapp-chat-info'),
    path('whatsapp/chats/<str:chat_id>/update/', whatsapp_update_chat, name='whatsapp-update-chat'),
    path('whatsapp/chats/<str:chat_id>/mark-read/', whatsapp_mark_chat_read, name='whatsapp-mark-chat-read'),
    path('whatsapp/chats/<str:chat_id>/assign-operator/', whatsapp_assign_chat_operator, name='whatsapp-assign-chat-operator'),
    path('whatsapp/send-message/', whatsapp_send_message, name='whatsapp-send-message'),
    path('whatsapp/groups/', whatsapp_groups, name='whatsapp-groups'),
    path('whatsapp/groups/<str:group_id>/info/', whatsapp_group_info, name='whatsapp-group-info'),
    path('whatsapp/groups/<str:group_id>/assign-operator/', whatsapp_assign_group_operator, name='whatsapp-assign-group-operator'),
    path('whatsapp/outreach/run-now/', whatsapp_outreach_run_now, name='whatsapp-outreach-run-now'),
    path('whatsapp/groups/<str:group_id>/outreach/', whatsapp_group_outreach, name='whatsapp-group-outreach'),
    path('whatsapp/groups/<str:group_id>/outreach/send-one/', whatsapp_group_outreach_send_one, name='whatsapp-group-outreach-send-one'),
    path('whatsapp/experiences/', whatsapp_experiences, name='whatsapp-experiences'),
    path('whatsapp/experiences/<str:experience_id>/group/', whatsapp_experience_group, name='whatsapp-experience-group'),
    path('whatsapp/accommodations/', whatsapp_accommodations, name='whatsapp-accommodations'),
    path('whatsapp/accommodations/<uuid:accommodation_id>/group/', whatsapp_accommodation_group, name='whatsapp-accommodation-group'),
    path('whatsapp/hotels/', whatsapp_hotels, name='whatsapp-hotels'),
    path('whatsapp/hotels/<uuid:hotel_id>/group/', whatsapp_hotel_group, name='whatsapp-hotel-group'),
    path('whatsapp/rental-hubs/', whatsapp_rental_hubs, name='whatsapp-rental-hubs'),
    path('whatsapp/rental-hubs/<uuid:rental_hub_id>/group/', whatsapp_rental_hub_group, name='whatsapp-rental-hub-group'),
    path('whatsapp/reservation-messages/', whatsapp_reservation_messages, name='whatsapp-reservation-messages'),
    path('whatsapp/experiences/<str:experience_id>/reservation-messages/', whatsapp_experience_reservation_messages, name='whatsapp-experience-reservation-messages'),
    path('whatsapp/accommodations/<uuid:accommodation_id>/reservation-messages/', whatsapp_accommodation_reservation_messages, name='whatsapp-accommodation-reservation-messages'),
    path('whatsapp/hotels/<uuid:hotel_id>/reservation-messages/', whatsapp_hotel_reservation_messages, name='whatsapp-hotel-reservation-messages'),
    path('whatsapp/rental-hubs/<uuid:rental_hub_id>/reservation-messages/', whatsapp_rental_hub_reservation_messages, name='whatsapp-rental-hub-reservation-messages'),
    path('whatsapp/operators/<str:operator_id>/', whatsapp_operator_detail, name='whatsapp-operator-detail'),
    path('whatsapp/operators/<str:operator_id>/default-group/', whatsapp_operator_default_group, name='whatsapp-operator-default-group'),
    
    # 🚀 ENTERPRISE: JSON upload (schema + create-from-json)
    path('schema/<str:entity>/', schema_for_entity, name='superadmin-schema'),
    path('experiences/create-from-json/', create_experience_from_json, name='create-experience-from-json'),
    path('accommodations/create-from-json/', create_accommodation_from_json, name='create-accommodation-from-json'),
    path('accommodations/bulk-upload-gallery-zip/', bulk_upload_gallery_zip, name='superadmin-accommodations-bulk-upload-gallery-zip'),
    path('experiences/<uuid:experience_id>/commission/', update_experience_commission, name='update-experience-commission'),
    path('experiences/<uuid:experience_id>/', superadmin_experience_detail, name='superadmin-experience-detail'),
    path('experiences/<uuid:experience_id>/landing-destinations/', experience_landing_destinations, name='superadmin-experience-landing-destinations'),
    path('experiences/<uuid:experience_id>/instances/', superadmin_experience_instances, name='superadmin-experience-instances'),
    path('experiences/<uuid:experience_id>/instances/block-by-date/', superadmin_experience_instances_block_by_date, name='superadmin-experience-instances-block-by-date'),
    path('experiences/<uuid:experience_id>/instances/unblock-by-date/', superadmin_experience_instances_unblock_by_date, name='superadmin-experience-instances-unblock-by-date'),
    path('experiences/<uuid:experience_id>/regenerate-instances/', superadmin_experience_regenerate_instances, name='superadmin-experience-regenerate-instances'),
    path('experiences/<uuid:experience_id>/instances/<uuid:instance_id>/bookings/', superadmin_experience_instance_bookings, name='superadmin-experience-instance-bookings'),
    path('experiences/<uuid:experience_id>/instances/<uuid:instance_id>/cancel-and-notify/', superadmin_experience_instance_cancel_and_notify, name='superadmin-experience-instance-cancel-and-notify'),
    path('experiences/<uuid:experience_id>/bookings-by-date/', superadmin_experience_bookings_by_date, name='superadmin-experience-bookings-by-date'),
    path('creators-landing-slots/', creators_landing_slots_list, name='creators-landing-slots-list'),
    path('creators-landing-slots/assign/', creators_landing_slots_assign, name='creators-landing-slots-assign'),
    path('creators/', SuperAdminCreatorsListView.as_view(), name='superadmin-creators-list'),
    # Accommodations (photo tour / gallery)
    path('accommodations/', SuperAdminAccommodationListView.as_view(), name='superadmin-accommodations-list'),
    path('accommodations/<uuid:accommodation_id>/', SuperAdminAccommodationDetailView.as_view(), name='superadmin-accommodations-detail'),
    path('accommodations/<uuid:accommodation_id>/from-json/', update_accommodation_from_json, name='superadmin-accommodations-update-from-json'),
    path('accommodations/<uuid:accommodation_id>/blocked-dates/', accommodation_blocked_dates, name='superadmin-accommodations-blocked-dates'),
    path('accommodations/<uuid:accommodation_id>/gallery/', SuperAdminAccommodationGalleryUpdateView.as_view(), name='superadmin-accommodations-gallery'),
    # Car rental (companies + cars)
    path('car-rental/companies/', SuperAdminCarRentalCompanyListView.as_view(), name='superadmin-car-rental-companies-list'),
    path('car-rental/companies/create-from-json/', create_car_rental_company_from_json, name='superadmin-car-rental-companies-create-from-json'),
    path('car-rental/companies/<uuid:pk>/', SuperAdminCarRentalCompanyDetailView.as_view(), name='superadmin-car-rental-company-detail'),
    path('car-rental/cars/', SuperAdminCarListView.as_view(), name='superadmin-car-rental-cars-list'),
    path('car-rental/cars/create-from-json/', create_car_from_json, name='superadmin-car-rental-cars-create-from-json'),
    path('car-rental/cars/<uuid:pk>/', SuperAdminCarDetailView.as_view(), name='superadmin-car-rental-car-detail'),
    path('car-rental/cars/<uuid:pk>/gallery/', SuperAdminCarGalleryUpdateView.as_view(), name='superadmin-car-rental-car-gallery'),
    # Erasmus: leads (list + export ?format=csv), detail (GET/PATCH), create-from-json
    path('erasmus/leads/', ErasmusLeadsView.as_view(), name='superadmin-erasmus-leads'),
    path('erasmus/leads/export/', ErasmusLeadsExportView.as_view(), name='superadmin-erasmus-leads-export'),
    path('erasmus/leads/create-from-json/', create_erasmus_leads_from_json, name='superadmin-erasmus-leads-create-from-json'),
    path('erasmus/leads/<str:lead_id>/', ErasmusLeadDetailView.as_view(), name='superadmin-erasmus-lead-detail'),
    path('erasmus/leads/<str:lead_id>/welcome-message/', ErasmusLeadWelcomeMessageView.as_view(), name='superadmin-erasmus-lead-welcome-message'),
    path('erasmus/welcome-message-templates/', ErasmusWelcomeMessageTemplatesView.as_view(), name='superadmin-erasmus-welcome-message-templates'),
    path('erasmus/timeline/create-from-json/', create_erasmus_timeline_from_json, name='superadmin-erasmus-timeline-create-from-json'),
    path('erasmus/activities/', ErasmusActivityListView.as_view(), name='superadmin-erasmus-activities-list'),
    path('erasmus/activities/create-from-json/', create_erasmus_activity_from_json, name='superadmin-erasmus-activities-create-from-json'),
    path('erasmus/activities/link-experience/', link_experience_to_erasmus_activity, name='superadmin-erasmus-activities-link-experience'),
    path('erasmus/activities/<uuid:activity_id>/', ErasmusActivityDetailView.as_view(), name='superadmin-erasmus-activity-detail'),
    path('erasmus/activities/<uuid:activity_id>/instances/', ErasmusActivityInstanceListCreateView.as_view(), name='superadmin-erasmus-activity-instances-list'),
    path('erasmus/activities/<uuid:activity_id>/instances/bulk-from-json/', erasmus_activity_instances_bulk_from_json, name='superadmin-erasmus-activity-instances-bulk-from-json'),
    path('erasmus/activities/<uuid:activity_id>/instances/<uuid:instance_id>/', ErasmusActivityInstanceDetailView.as_view(), name='superadmin-erasmus-activity-instance-detail'),
    path('erasmus/activities/<uuid:activity_id>/instances/<uuid:instance_id>/inscriptions/', ErasmusActivityInstanceInscriptionsView.as_view(), name='superadmin-erasmus-activity-instance-inscriptions'),
    path('erasmus/inscription-payments/<int:payment_id>/exclude_from_revenue/', erasmus_inscription_payment_exclude_from_revenue, name='superadmin-erasmus-inscription-payment-exclude-from-revenue'),
    path('erasmus/activities/<uuid:activity_id>/extra-fields/', ErasmusActivityExtraFieldViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-erasmus-activity-extra-fields'),
    path('erasmus/activities/<uuid:activity_id>/extra-fields/<int:pk>/', ErasmusActivityExtraFieldViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-erasmus-activity-extra-field-detail'),
    path('erasmus/activities/<uuid:activity_id>/public-link/', ErasmusActivityPublicLinkView.as_view(), name='superadmin-erasmus-activity-public-link'),
    path('erasmus/activities/<uuid:activity_id>/reviews/', ErasmusActivityReviewsListView.as_view(), name='superadmin-erasmus-activity-reviews'),
    path('erasmus/activities/<uuid:activity_id>/reviews/<int:review_id>/', ErasmusActivityReviewDeleteView.as_view(), name='superadmin-erasmus-activity-review-delete'),
    path('erasmus/dashboard/', ErasmusDashboardView.as_view(), name='superadmin-erasmus-dashboard'),
    path('erasmus/tracking-links/', ErasmusTrackingLinkViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-erasmus-tracking-links'),
    path('erasmus/tracking-links/<int:pk>/', ErasmusTrackingLinkViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-erasmus-tracking-link-detail'),
    path('erasmus/extra-fields/', ErasmusExtraFieldViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-erasmus-extra-fields'),
    path('erasmus/extra-fields/<int:pk>/', ErasmusExtraFieldViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-erasmus-extra-field-detail'),
    path('erasmus/destination-guides/', ErasmusDestinationGuideViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-erasmus-destination-guides'),
    path('erasmus/destination-guides/<int:pk>/', ErasmusDestinationGuideViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-erasmus-destination-guide-detail'),
    path('erasmus/local-partners/', ErasmusLocalPartnerViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-erasmus-local-partners'),
    path('erasmus/local-partners/<int:pk>/', ErasmusLocalPartnerViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-erasmus-local-partner-detail'),
    path('erasmus/whatsapp-groups/', ErasmusWhatsAppGroupViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-erasmus-whatsapp-groups'),
    path('erasmus/whatsapp-groups/bulk-from-json/', erasmus_whatsapp_groups_bulk_from_json, name='superadmin-erasmus-whatsapp-groups-bulk-from-json'),
    path('erasmus/whatsapp-groups/<int:pk>/fetch-image/', erasmus_whatsapp_group_fetch_image, name='superadmin-erasmus-whatsapp-group-fetch-image'),
    path('erasmus/whatsapp-groups/<int:pk>/', ErasmusWhatsAppGroupViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-erasmus-whatsapp-group-detail'),
    path('erasmus/partner-notifications/rumi-housing/', ErasmusRumiNotificationConfigView.as_view(), name='superadmin-erasmus-rumi-notification-config'),
    path('erasmus-slides/', erasmus_slides_list, name='superadmin-erasmus-slides-list'),
    path('erasmus-slides/assign/', erasmus_slides_assign, name='superadmin-erasmus-slides-assign'),
    path('erasmus-slides/create/', erasmus_slides_create, name='superadmin-erasmus-slides-create'),
    path('erasmus-slides/delete/', erasmus_slides_delete, name='superadmin-erasmus-slides-delete'),
    path('erasmus-slides/reorder/', erasmus_slides_reorder, name='superadmin-erasmus-slides-reorder'),
    path('erasmus-slides/<str:slide_id>/', erasmus_slides_delete, name='superadmin-erasmus-slides-delete-by-id'),
    # Contests / Sorteos
    path('contests/', ContestListView.as_view(), name='superadmin-contests-list'),
    path('contests/create/', ContestCreateView.as_view(), name='superadmin-contests-create'),
    path('contests/<int:pk>/', ContestDetailView.as_view(), name='superadmin-contest-detail'),
    path('contests/<int:contest_id>/slides/', ContestSlidesView.as_view(), name='superadmin-contest-slides'),
    path('contests/<int:contest_id>/slides/assign/', ContestSlideAssignView.as_view(), name='superadmin-contest-slides-assign'),
    path('contests/<int:contest_id>/slides/reorder/', ContestSlidesReorderView.as_view(), name='superadmin-contest-slides-reorder'),
    path('contests/<int:contest_id>/slides/<uuid:slide_id>/', ContestSlideDeleteView.as_view(), name='superadmin-contest-slide-delete'),
    path('contests/<int:contest_id>/extra-fields/', ContestExtraFieldViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-contest-extra-fields'),
    path('contests/<int:contest_id>/extra-fields/<int:pk>/', ContestExtraFieldViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-contest-extra-field-detail'),
    path('contests/<int:contest_id>/participants/', ContestParticipantsView.as_view(), name='superadmin-contest-participants'),
    path('contests/<int:contest_id>/participants/export/', ContestParticipantsExportView.as_view(), name='superadmin-contest-participants-export'),
    # Vitrina del hero (landing principal)
    path('hero-vitrina/', hero_vitrina_list, name='superadmin-hero-vitrina-list'),
    path('hero-vitrina/add/', hero_vitrina_add, name='superadmin-hero-vitrina-add'),
    path('hero-vitrina/reorder/', hero_vitrina_reorder, name='superadmin-hero-vitrina-reorder'),
    path('hero-vitrina/<uuid:item_id>/', hero_vitrina_remove, name='superadmin-hero-vitrina-remove'),
    # Fondo del formulario de registro Erasmus
    path('erasmus-registro-background/', erasmus_registro_background_list, name='superadmin-erasmus-registro-background-list'),
    path('erasmus-registro-background/create/', erasmus_registro_background_create, name='superadmin-erasmus-registro-background-create'),
    path('erasmus-registro-background/reorder/', erasmus_registro_background_reorder, name='superadmin-erasmus-registro-background-reorder'),
    path('erasmus-registro-background/assign/', erasmus_registro_background_assign, name='superadmin-erasmus-registro-background-assign'),
    path('erasmus-registro-background/<uuid:pk>/', erasmus_registro_background_delete, name='superadmin-erasmus-registro-background-delete'),
    # Fondo de login/auth (login, registro, organizer login)
    path('auth-background/', auth_background_list, name='superadmin-auth-background-list'),
    path('auth-background/create/', auth_background_create, name='superadmin-auth-background-create'),
    path('auth-background/reorder/', auth_background_reorder, name='superadmin-auth-background-reorder'),
    path('auth-background/assign/', auth_background_assign, name='superadmin-auth-background-assign'),
    path('auth-background/<uuid:pk>/', auth_background_delete, name='superadmin-auth-background-delete'),
]

