"""URL Configuration for Super Admin API."""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from apps.landing_destinations.views import LandingDestinationViewSet
from .views.rental_hubs import RentalHubViewSet
from .views.hotels import HotelViewSet, create_hotel_from_json, update_hotel_from_json
from .views import (
    SuperAdminUserViewSet,
    CountryViewSet,
    platform_status,
    platform_uptime_report,
    SuperAdminAccommodationListView,
    SuperAdminAccommodationDetailView,
    SuperAdminAccommodationGalleryUpdateView,
    create_accommodation_from_json,
    update_accommodation_from_json,
    accommodation_blocked_dates,
    SuperAdminCarRentalCompanyListView,
    SuperAdminCarRentalCompanyDetailView,
    SuperAdminCarListView,
    SuperAdminCarDetailView,
    SuperAdminCarGalleryUpdateView,
    create_car_rental_company_from_json,
    create_car_from_json,
    schema_for_entity,
    create_destination_from_json,
    ErasmusLeadsView,
    ErasmusLeadsExportView,
    ErasmusLeadDetailView,
    ErasmusLeadWelcomeMessageView,
    ErasmusDashboardView,
    create_erasmus_leads_from_json,
    create_erasmus_timeline_from_json,
    create_erasmus_activity_from_json,
    link_experience_to_erasmus_activity,
    ErasmusActivityListView,
    ErasmusActivityDetailView,
    ErasmusActivityInstanceListCreateView,
    ErasmusActivityInstanceDetailView,
    ErasmusActivityInstanceInscriptionsView,
    ErasmusActivityPublicLinkView,
    ErasmusActivityReviewsListView,
    ErasmusActivityReviewDeleteView,
    erasmus_activity_instances_bulk_from_json,
    ErasmusTrackingLinkViewSet,
    ErasmusExtraFieldViewSet,
    ErasmusDestinationGuideViewSet,
    ErasmusLocalPartnerViewSet,
    ErasmusWhatsAppGroupViewSet,
    erasmus_whatsapp_groups_bulk_from_json,
    erasmus_whatsapp_group_fetch_image,
    ErasmusRumiNotificationConfigView,
    erasmus_slides_list,
    erasmus_slides_assign,
    erasmus_slides_create,
    erasmus_slides_delete,
    erasmus_slides_reorder,
    erasmus_registro_background_list,
    erasmus_registro_background_create,
    erasmus_registro_background_delete,
    erasmus_registro_background_assign,
    erasmus_registro_background_reorder,
    superadmin_stats, 
    sales_analytics, 
    organizer_sales, 
    events_analytics, 
    update_organizer_template,
    update_organizer_modules,
    update_organizer_service_fee,
    update_event_service_fee,
    get_event_detail,
    update_ticket_tier_service_fee,
    # 🚀 ENTERPRISE: Platform Flow Monitoring
    ticket_delivery_funnel,
    ticket_delivery_issues,
    all_flows,
    flow_detail,
    resend_order_email,
    bulk_resend_emails,
    celery_tasks_list,
    historical_conversion_rates,
    events_list,
    # 🚀 ENTERPRISE: Revenue Migration
    revenue_migration_status,
    migrate_revenue_data,
    # Finances
    pending_payouts,
    create_payout,
    export_payouts,
    bank_options,
    # 🚀 ENTERPRISE: JSON Experience Creation
    create_experience_from_json,
    update_experience_commission,
    creators_landing_slots_list,
    creators_landing_slots_assign,
    SuperAdminCreatorsListView,
)
from .whatsapp_views import (
    whatsapp_status,
    whatsapp_disconnect,
    whatsapp_qr,
    whatsapp_request_new_qr,
    whatsapp_profile_picture,
    whatsapp_reservations,
    whatsapp_operators,
    whatsapp_bind_experience_operator,
    whatsapp_messages,
    whatsapp_mark_message_reservation,
    whatsapp_chats,
    whatsapp_chat_info,
    whatsapp_update_chat,
    whatsapp_mark_chat_read,
    whatsapp_assign_chat_operator,
    whatsapp_sync_chats,
    whatsapp_send_message,
    whatsapp_groups,
    whatsapp_group_info,
    whatsapp_assign_group_operator,
    whatsapp_group_outreach,
    whatsapp_experiences,
    whatsapp_experience_group,
    whatsapp_operator_detail,
    whatsapp_operator_default_group,
)

# Create router
router = DefaultRouter()
router.register(r'users', SuperAdminUserViewSet, basename='superadmin-users')
router.register(r'countries', CountryViewSet, basename='country')
router.register(r'destinations', LandingDestinationViewSet, basename='superadmin-destinations')
router.register(r'rental-hubs', RentalHubViewSet, basename='superadmin-rental-hubs')
router.register(r'hotels', HotelViewSet, basename='superadmin-hotels')

urlpatterns = [
    # Rutas específicas ANTES del router para que no sean capturadas por destinations/<pk>/
    path('destinations/create-from-json/', create_destination_from_json, name='create-destination-from-json'),
    path('', include(router.urls)),
    path('platform-status/', platform_status, name='superadmin-platform-status'),
    path('platform-uptime-report/', platform_uptime_report, name='superadmin-platform-uptime-report'),
    path('stats/', superadmin_stats, name='superadmin-stats'),
    path('sales-analytics/', sales_analytics, name='sales-analytics'),
    path('organizer-sales/', organizer_sales, name='organizer-sales'),
    path('events-analytics/', events_analytics, name='events-analytics'),
    path('organizers/<str:organizer_id>/template/', update_organizer_template, name='update-organizer-template'),
    path('organizers/<str:organizer_id>/modules/', update_organizer_modules, name='update-organizer-modules'),
    path('organizers/<str:organizer_id>/service-fee/', update_organizer_service_fee, name='update-organizer-service-fee'),
    path('events/<str:event_id>/ticket-tiers/<str:tier_id>/service-fee/', update_ticket_tier_service_fee, name='update-ticket-tier-service-fee'),
    path('events/<str:event_id>/', get_event_detail, name='superadmin-event-detail'),
    path('events/<str:event_id>/service-fee/', update_event_service_fee, name='update-event-service-fee'),
    
    # 🚀 ENTERPRISE: Platform Flow Monitoring Endpoints
    path('ticket-delivery-funnel/', ticket_delivery_funnel, name='ticket-delivery-funnel'),
    path('ticket-delivery-issues/', ticket_delivery_issues, name='ticket-delivery-issues'),
    path('events-list/', events_list, name='events-list'),
    path('flows/', all_flows, name='all-flows'),
    # IMPORTANT: Specific paths must come before generic ones
    path('flows/bulk-resend-emails/', bulk_resend_emails, name='bulk-resend-emails'),
    path('flows/<str:flow_id>/resend-email/', resend_order_email, name='resend-order-email'),
    path('flows/<str:flow_id>/', flow_detail, name='flow-detail'),
    path('celery-tasks/', celery_tasks_list, name='celery-tasks-list'),
    path('historical-conversion-rates/', historical_conversion_rates, name='historical-conversion-rates'),
    
    # 🚀 ENTERPRISE: Revenue Migration Endpoints
    path('revenue-migration/status/', revenue_migration_status, name='revenue-migration-status'),
    path('revenue-migration/migrate/', migrate_revenue_data, name='migrate-revenue-data'),
    path('pending-payouts/', pending_payouts, name='pending-payouts'),
    path('pending-payouts/export/', export_payouts, name='export-payouts'),
    path('payouts/', create_payout, name='create-payout'),
    path('bank-options/', bank_options, name='bank-options'),
    # 🚀 ENTERPRISE: WhatsApp Integration Endpoints
    path('whatsapp/status/', whatsapp_status, name='whatsapp-status'),
    path('whatsapp/disconnect/', whatsapp_disconnect, name='whatsapp-disconnect'),
    path('whatsapp/qr/', whatsapp_qr, name='whatsapp-qr'),
    path('whatsapp/request-new-qr/', whatsapp_request_new_qr, name='whatsapp-request-new-qr'),
    path('whatsapp/reservations/', whatsapp_reservations, name='whatsapp-reservations'),
    path('whatsapp/operators/', whatsapp_operators, name='whatsapp-operators'),
    path('whatsapp/bind-experience-operator/', whatsapp_bind_experience_operator, name='whatsapp-bind-experience-operator'),
    path('whatsapp/messages/', whatsapp_messages, name='whatsapp-messages'),
    path('whatsapp/messages/<str:message_id>/mark-reservation/', whatsapp_mark_message_reservation, name='whatsapp-mark-message-reservation'),
    path('whatsapp/chats/', whatsapp_chats, name='whatsapp-chats'),
    path('whatsapp/profile-picture/<str:chat_id>/', whatsapp_profile_picture, name='whatsapp-profile-picture'),
    path('whatsapp/chats/sync/', whatsapp_sync_chats, name='whatsapp-sync-chats'),
    path('whatsapp/chats/<str:chat_id>/', whatsapp_chat_info, name='whatsapp-chat-info'),
    path('whatsapp/chats/<str:chat_id>/update/', whatsapp_update_chat, name='whatsapp-update-chat'),
    path('whatsapp/chats/<str:chat_id>/mark-read/', whatsapp_mark_chat_read, name='whatsapp-mark-chat-read'),
    path('whatsapp/chats/<str:chat_id>/assign-operator/', whatsapp_assign_chat_operator, name='whatsapp-assign-chat-operator'),
    path('whatsapp/send-message/', whatsapp_send_message, name='whatsapp-send-message'),
    path('whatsapp/groups/', whatsapp_groups, name='whatsapp-groups'),
    path('whatsapp/groups/<str:group_id>/info/', whatsapp_group_info, name='whatsapp-group-info'),
    path('whatsapp/groups/<str:group_id>/assign-operator/', whatsapp_assign_group_operator, name='whatsapp-assign-group-operator'),
    path('whatsapp/groups/<str:group_id>/outreach/', whatsapp_group_outreach, name='whatsapp-group-outreach'),
    path('whatsapp/experiences/', whatsapp_experiences, name='whatsapp-experiences'),
    path('whatsapp/experiences/<str:experience_id>/group/', whatsapp_experience_group, name='whatsapp-experience-group'),
    path('whatsapp/operators/<str:operator_id>/', whatsapp_operator_detail, name='whatsapp-operator-detail'),
    path('whatsapp/operators/<str:operator_id>/default-group/', whatsapp_operator_default_group, name='whatsapp-operator-default-group'),
    
    # 🚀 ENTERPRISE: JSON upload (schema + create-from-json)
    path('schema/<str:entity>/', schema_for_entity, name='superadmin-schema'),
    path('experiences/create-from-json/', create_experience_from_json, name='create-experience-from-json'),
    path('accommodations/create-from-json/', create_accommodation_from_json, name='create-accommodation-from-json'),
    path('hotels/create-from-json/', create_hotel_from_json, name='create-hotel-from-json'),
    path('hotels/<uuid:hotel_id>/from-json/', update_hotel_from_json, name='update-hotel-from-json'),
    path('experiences/<uuid:experience_id>/commission/', update_experience_commission, name='update-experience-commission'),
    path('creators-landing-slots/', creators_landing_slots_list, name='creators-landing-slots-list'),
    path('creators-landing-slots/assign/', creators_landing_slots_assign, name='creators-landing-slots-assign'),
    path('creators/', SuperAdminCreatorsListView.as_view(), name='superadmin-creators-list'),
    # Accommodations (photo tour / gallery)
    path('accommodations/', SuperAdminAccommodationListView.as_view(), name='superadmin-accommodations-list'),
    path('accommodations/<uuid:accommodation_id>/', SuperAdminAccommodationDetailView.as_view(), name='superadmin-accommodations-detail'),
    path('accommodations/<uuid:accommodation_id>/from-json/', update_accommodation_from_json, name='superadmin-accommodations-update-from-json'),
    path('accommodations/<uuid:accommodation_id>/blocked-dates/', accommodation_blocked_dates, name='superadmin-accommodations-blocked-dates'),
    path('accommodations/<uuid:accommodation_id>/gallery/', SuperAdminAccommodationGalleryUpdateView.as_view(), name='superadmin-accommodations-gallery'),
    # Car rental (companies + cars)
    path('car-rental/companies/', SuperAdminCarRentalCompanyListView.as_view(), name='superadmin-car-rental-companies-list'),
    path('car-rental/companies/create-from-json/', create_car_rental_company_from_json, name='superadmin-car-rental-companies-create-from-json'),
    path('car-rental/companies/<uuid:pk>/', SuperAdminCarRentalCompanyDetailView.as_view(), name='superadmin-car-rental-company-detail'),
    path('car-rental/cars/', SuperAdminCarListView.as_view(), name='superadmin-car-rental-cars-list'),
    path('car-rental/cars/create-from-json/', create_car_from_json, name='superadmin-car-rental-cars-create-from-json'),
    path('car-rental/cars/<uuid:pk>/', SuperAdminCarDetailView.as_view(), name='superadmin-car-rental-car-detail'),
    path('car-rental/cars/<uuid:pk>/gallery/', SuperAdminCarGalleryUpdateView.as_view(), name='superadmin-car-rental-car-gallery'),
    # Erasmus: leads (list + export ?format=csv), detail (GET/PATCH), create-from-json
    path('erasmus/leads/', ErasmusLeadsView.as_view(), name='superadmin-erasmus-leads'),
    path('erasmus/leads/export/', ErasmusLeadsExportView.as_view(), name='superadmin-erasmus-leads-export'),
    path('erasmus/leads/create-from-json/', create_erasmus_leads_from_json, name='superadmin-erasmus-leads-create-from-json'),
    path('erasmus/leads/<str:lead_id>/', ErasmusLeadDetailView.as_view(), name='superadmin-erasmus-lead-detail'),
    path('erasmus/leads/<str:lead_id>/welcome-message/', ErasmusLeadWelcomeMessageView.as_view(), name='superadmin-erasmus-lead-welcome-message'),
    path('erasmus/timeline/create-from-json/', create_erasmus_timeline_from_json, name='superadmin-erasmus-timeline-create-from-json'),
    path('erasmus/activities/', ErasmusActivityListView.as_view(), name='superadmin-erasmus-activities-list'),
    path('erasmus/activities/create-from-json/', create_erasmus_activity_from_json, name='superadmin-erasmus-activities-create-from-json'),
    path('erasmus/activities/link-experience/', link_experience_to_erasmus_activity, name='superadmin-erasmus-activities-link-experience'),
    path('erasmus/activities/<uuid:activity_id>/', ErasmusActivityDetailView.as_view(), name='superadmin-erasmus-activity-detail'),
    path('erasmus/activities/<uuid:activity_id>/instances/', ErasmusActivityInstanceListCreateView.as_view(), name='superadmin-erasmus-activity-instances-list'),
    path('erasmus/activities/<uuid:activity_id>/instances/bulk-from-json/', erasmus_activity_instances_bulk_from_json, name='superadmin-erasmus-activity-instances-bulk-from-json'),
    path('erasmus/activities/<uuid:activity_id>/instances/<uuid:instance_id>/', ErasmusActivityInstanceDetailView.as_view(), name='superadmin-erasmus-activity-instance-detail'),
    path('erasmus/activities/<uuid:activity_id>/instances/<uuid:instance_id>/inscriptions/', ErasmusActivityInstanceInscriptionsView.as_view(), name='superadmin-erasmus-activity-instance-inscriptions'),
    path('erasmus/activities/<uuid:activity_id>/public-link/', ErasmusActivityPublicLinkView.as_view(), name='superadmin-erasmus-activity-public-link'),
    path('erasmus/activities/<uuid:activity_id>/reviews/', ErasmusActivityReviewsListView.as_view(), name='superadmin-erasmus-activity-reviews'),
    path('erasmus/activities/<uuid:activity_id>/reviews/<int:review_id>/', ErasmusActivityReviewDeleteView.as_view(), name='superadmin-erasmus-activity-review-delete'),
    path('erasmus/dashboard/', ErasmusDashboardView.as_view(), name='superadmin-erasmus-dashboard'),
    path('erasmus/tracking-links/', ErasmusTrackingLinkViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-erasmus-tracking-links'),
    path('erasmus/tracking-links/<int:pk>/', ErasmusTrackingLinkViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-erasmus-tracking-link-detail'),
    path('erasmus/extra-fields/', ErasmusExtraFieldViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-erasmus-extra-fields'),
    path('erasmus/extra-fields/<int:pk>/', ErasmusExtraFieldViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-erasmus-extra-field-detail'),
    path('erasmus/destination-guides/', ErasmusDestinationGuideViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-erasmus-destination-guides'),
    path('erasmus/destination-guides/<int:pk>/', ErasmusDestinationGuideViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-erasmus-destination-guide-detail'),
    path('erasmus/local-partners/', ErasmusLocalPartnerViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-erasmus-local-partners'),
    path('erasmus/local-partners/<int:pk>/', ErasmusLocalPartnerViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-erasmus-local-partner-detail'),
    path('erasmus/whatsapp-groups/', ErasmusWhatsAppGroupViewSet.as_view({'get': 'list', 'post': 'create'}), name='superadmin-erasmus-whatsapp-groups'),
    path('erasmus/whatsapp-groups/bulk-from-json/', erasmus_whatsapp_groups_bulk_from_json, name='superadmin-erasmus-whatsapp-groups-bulk-from-json'),
    path('erasmus/whatsapp-groups/<int:pk>/fetch-image/', erasmus_whatsapp_group_fetch_image, name='superadmin-erasmus-whatsapp-group-fetch-image'),
    path('erasmus/whatsapp-groups/<int:pk>/', ErasmusWhatsAppGroupViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='superadmin-erasmus-whatsapp-group-detail'),
    path('erasmus/partner-notifications/rumi-housing/', ErasmusRumiNotificationConfigView.as_view(), name='superadmin-erasmus-rumi-notification-config'),
    path('erasmus-slides/', erasmus_slides_list, name='superadmin-erasmus-slides-list'),
    path('erasmus-slides/assign/', erasmus_slides_assign, name='superadmin-erasmus-slides-assign'),
    path('erasmus-slides/create/', erasmus_slides_create, name='superadmin-erasmus-slides-create'),
    path('erasmus-slides/delete/', erasmus_slides_delete, name='superadmin-erasmus-slides-delete'),
    path('erasmus-slides/reorder/', erasmus_slides_reorder, name='superadmin-erasmus-slides-reorder'),
    path('erasmus-slides/<str:slide_id>/', erasmus_slides_delete, name='superadmin-erasmus-slides-delete-by-id'),
    # Fondo del formulario de registro Erasmus
    path('erasmus-registro-background/', erasmus_registro_background_list, name='superadmin-erasmus-registro-background-list'),
    path('erasmus-registro-background/create/', erasmus_registro_background_create, name='superadmin-erasmus-registro-background-create'),
    path('erasmus-registro-background/reorder/', erasmus_registro_background_reorder, name='superadmin-erasmus-registro-background-reorder'),
    path('erasmus-registro-background/assign/', erasmus_registro_background_assign, name='superadmin-erasmus-registro-background-assign'),
    path('erasmus-registro-background/<uuid:pk>/', erasmus_registro_background_delete, name='superadmin-erasmus-registro-background-delete'),
]

