# Generated by Django 4.2.8 on 2026-02-01 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationCheckpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre descriptivo del checkpoint', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Descripción de qué contiene este checkpoint', verbose_name='description')),
                ('snapshot_file_path', models.CharField(help_text='Ruta del archivo con el snapshot de datos', max_length=500, verbose_name='snapshot file path')),
                ('snapshot_size_mb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='snapshot size (MB)')),
                ('total_models', models.IntegerField(default=0, verbose_name='total models')),
                ('total_records', models.IntegerField(default=0, verbose_name='total records')),
                ('total_files', models.IntegerField(default=0, verbose_name='total files')),
                ('database_version', models.CharField(blank=True, max_length=100, verbose_name='database version')),
                ('environment', models.CharField(blank=True, help_text='Entorno donde se creó (GCP, Local, etc)', max_length=50, verbose_name='environment')),
                ('is_valid', models.BooleanField(default=True, help_text='Si el checkpoint es válido y puede usarse para restore', verbose_name='is valid')),
                ('used_for_restore', models.BooleanField(default=False, help_text='Si este checkpoint fue usado para hacer restore', verbose_name='used for restore')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='restored at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del checkpoint', null=True, verbose_name='expires at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_checkpoints', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'migration checkpoint',
                'verbose_name_plural': 'migration checkpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('export', 'Export'), ('import', 'Import'), ('push', 'Push to Target'), ('pull', 'Pull from Source')], max_length=20, verbose_name='direction')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rolling_back', 'Rolling Back'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20, verbose_name='status')),
                ('source_url', models.URLField(blank=True, help_text='URL del backend origen (para pull)', null=True, verbose_name='source URL')),
                ('target_url', models.URLField(blank=True, help_text='URL del backend destino (para push)', null=True, verbose_name='target URL')),
                ('auth_token_hash', models.CharField(blank=True, help_text='Hash del token de autenticación', max_length=255, verbose_name='auth token hash')),
                ('progress_percent', models.IntegerField(default=0, help_text='Porcentaje de progreso (0-100)', verbose_name='progress percentage')),
                ('current_step', models.CharField(blank=True, help_text='Descripción del paso actual', max_length=255, verbose_name='current step')),
                ('export_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='export file path')),
                ('export_file_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='export file size (MB)')),
                ('total_models', models.IntegerField(default=0, verbose_name='total models')),
                ('models_completed', models.IntegerField(default=0, verbose_name='models completed')),
                ('total_records', models.IntegerField(default=0, verbose_name='total records')),
                ('records_processed', models.IntegerField(default=0, verbose_name='records processed')),
                ('total_files', models.IntegerField(default=0, verbose_name='total files')),
                ('files_transferred', models.IntegerField(default=0, verbose_name='files transferred')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='duration (seconds)')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la migración falló', verbose_name='error message')),
                ('error_traceback', models.TextField(blank=True, help_text='Traceback completo del error', verbose_name='error traceback')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuración usada para esta migración', verbose_name='configuration')),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_jobs', to='migration_system.migrationcheckpoint', verbose_name='checkpoint')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_jobs', to=settings.AUTH_USER_MODEL, verbose_name='executed by')),
            ],
            options={
                'verbose_name': 'migration job',
                'verbose_name_plural': 'migration jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='Token único para autenticación', max_length=255, unique=True, verbose_name='token')),
                ('description', models.CharField(help_text='Descripción del propósito del token', max_length=255, verbose_name='description')),
                ('permissions', models.CharField(choices=[('read', 'Read Only'), ('write', 'Write Only'), ('read_write', 'Read and Write'), ('admin', 'Admin (Full Access)')], default='read_write', max_length=20, verbose_name='permissions')),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='Lista de IPs permitidas (vacío = todas)', verbose_name='allowed IPs')),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text='Lista de dominios permitidos', verbose_name='allowed domains')),
                ('expires_at', models.DateTimeField(help_text='Fecha y hora de expiración del token', verbose_name='expires at')),
                ('is_single_use', models.BooleanField(default=False, help_text='Si el token solo puede usarse una vez', verbose_name='is single use')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('usage_count', models.IntegerField(default=0, verbose_name='usage count')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last used IP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_tokens', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_migration_tokens', to=settings.AUTH_USER_MODEL, verbose_name='revoked by')),
            ],
            options={
                'verbose_name': 'migration token',
                'verbose_name_plural': 'migration tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='migration_s_token_f770ba_idx'), models.Index(fields=['expires_at'], name='migration_s_expires_998d8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MigrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='level')),
                ('message', models.TextField(help_text='Mensaje del log', verbose_name='message')),
                ('model_name', models.CharField(blank=True, help_text='Modelo afectado (ej: events.Event)', max_length=100, verbose_name='model name')),
                ('record_count', models.IntegerField(blank=True, help_text='Cantidad de registros procesados', null=True, verbose_name='record count')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duración de la operación en milisegundos', null=True, verbose_name='duration (ms)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre la operación', verbose_name='metadata')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='migration_system.migrationjob', verbose_name='migration job')),
            ],
            options={
                'verbose_name': 'migration log',
                'verbose_name_plural': 'migration logs',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['job', 'timestamp'], name='migration_s_job_id_d63b6b_idx'), models.Index(fields=['job', 'level'], name='migration_s_job_id_1e6f0f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='migrationjob',
            index=models.Index(fields=['status', 'created_at'], name='migration_s_status_5995e5_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationjob',
            index=models.Index(fields=['direction', 'status'], name='migration_s_directi_b94993_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationcheckpoint',
            index=models.Index(fields=['is_valid', 'created_at'], name='migration_s_is_vali_09b5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationcheckpoint',
            index=models.Index(fields=['environment', 'created_at'], name='migration_s_environ_ceb08f_idx'),
        ),
    ]
