# Generated by Django 4.2.8 on 2026-02-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationlog',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text='Modelo afectado (ej: events.Event)', max_length=100, null=True, verbose_name='model name'),
        ),
    ]
