# Generated by Django 4.2.8 on 2026-02-01 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('migration_system', '0002_alter_migrationlog_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_file', models.FileField(help_text='Archivo .tar.gz con el backup de GCP', upload_to='backups/%Y/%m/', verbose_name='backup file')),
                ('file_size_mb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='file size (MB)')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validating', 'Validating'), ('validated', 'Validated'), ('restoring', 'Restoring'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=20, verbose_name='status')),
                ('progress_percent', models.IntegerField(default=0, verbose_name='progress percentage')),
                ('current_step', models.CharField(blank=True, max_length=255, verbose_name='current step')),
                ('restore_sql', models.BooleanField(default=True, help_text='Restaurar base de datos PostgreSQL', verbose_name='restore SQL')),
                ('restore_media', models.BooleanField(default=True, help_text='Restaurar archivos media', verbose_name='restore media')),
                ('create_backup_before', models.BooleanField(default=True, help_text='Crear backup de seguridad antes de restaurar', verbose_name='create backup before')),
                ('backup_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata extraída del backup (timestamp, counts, etc)', verbose_name='backup metadata')),
                ('sql_records_restored', models.IntegerField(default=0, verbose_name='SQL records restored')),
                ('media_files_restored', models.IntegerField(default=0, verbose_name='media files restored')),
                ('media_size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='media size (MB)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='duration (seconds)')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('error_traceback', models.TextField(blank=True, verbose_name='error traceback')),
                ('safety_backup_path', models.CharField(blank=True, help_text='Ruta del backup de seguridad creado antes del restore', max_length=500, verbose_name='safety backup path')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_jobs', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'backup job',
                'verbose_name_plural': 'backup jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='migration_s_status_a96811_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='migration_s_uploade_1c7d20_idx')],
            },
        ),
    ]
