# Generated by Django 4.2.8 on 2025-12-01 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0037_add_ticket_tier_availability_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizers', '0013_organizer_experience_dashboard_template'),
        ('experiences', '0001_initial'),
        ('payment_processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFlow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flow_type', models.CharField(choices=[('ticket_checkout', 'Ticket Checkout (Events)'), ('experience_booking', 'Experience Booking'), ('accommodation_booking', 'Accommodation Booking'), ('tour_booking', 'Tour Booking')], db_index=True, help_text='Type of business flow being tracked', max_length=50)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', help_text='Current status of the flow', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, help_text='When the flow completed successfully', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When the flow failed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional flow-specific data (totals, session info, etc.)')),
                ('event', models.ForeignKey(blank=True, help_text='Event associated with this flow (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='events.event')),
                ('experience', models.ForeignKey(blank=True, help_text='Experience associated with this flow (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='experiences.experience')),
                ('organizer', models.ForeignKey(blank=True, help_text='Organizer associated with the flow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='organizers.organizer')),
                ('primary_order', models.ForeignKey(blank=True, help_text='Primary order created in this flow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_flows', to='events.order')),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the flow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Flow',
                'verbose_name_plural': 'Platform Flows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CeleryTaskLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, help_text='Celery task UUID (unique per execution)', max_length=255)),
                ('task_name', models.CharField(db_index=True, help_text='Full task path (e.g., apps.events.tasks.send_order_confirmation_email)', max_length=255)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failure', 'Failure'), ('retry', 'Retry')], db_index=True, help_text='Current status of the task execution', max_length=20)),
                ('queue', models.CharField(blank=True, help_text="Celery queue name (e.g., 'emails', 'critical')", max_length=100)),
                ('routing_key', models.CharField(blank=True, help_text='Routing key used for task', max_length=100)),
                ('args', models.JSONField(blank=True, default=list, help_text='Positional arguments passed to task')),
                ('kwargs', models.JSONField(blank=True, default=dict, help_text='Keyword arguments passed to task')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Task return value (if successful)')),
                ('error', models.TextField(blank=True, help_text='Error message if task failed')),
                ('traceback', models.TextField(blank=True, help_text='Full Python traceback if task failed')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Task execution duration in milliseconds', null=True)),
                ('flow', models.ForeignKey(blank=True, help_text='Flow this task belongs to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celery_logs', to='core.platformflow')),
                ('order', models.ForeignKey(blank=True, help_text='Order this task is processing (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celery_logs', to='events.order')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this task (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Celery Task Log',
                'verbose_name_plural': 'Celery Task Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFlowEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('RESERVATION_REQUESTED', 'Reservation Requested'), ('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_EXPIRED', 'Reservation Expired'), ('ORDER_CREATED', 'Order Created'), ('ORDER_MARKED_PAID', 'Order Marked as Paid'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_REFUNDED', 'Order Refunded'), ('PAYMENT_REQUIRED', 'Payment Required'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_AUTHORIZED', 'Payment Authorized'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_CANCELLED', 'Payment Cancelled'), ('HOLDER_DATA_STORED', 'Ticket Holder Data Stored'), ('TICKETS_CREATED', 'Tickets Created'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('EMAIL_TASK_ENQUEUED', 'Email Task Enqueued'), ('EMAIL_TASK_STARTED', 'Email Task Started'), ('EMAIL_SENT', 'Email Sent Successfully'), ('EMAIL_FAILED', 'Email Failed'), ('COUPON_APPLIED', 'Coupon Applied'), ('COUPON_VALIDATION_FAILED', 'Coupon Validation Failed'), ('FLOW_COMPLETED', 'Flow Completed Successfully'), ('FLOW_FAILED', 'Flow Failed'), ('FLOW_ABANDONED', 'Flow Abandoned')], db_index=True, help_text='Specific step in the flow', max_length=50)),
                ('source', models.CharField(choices=[('api', 'API'), ('celery', 'Celery Task'), ('payment_gateway', 'Payment Gateway'), ('system', 'System')], default='api', help_text='Source that generated this event', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('info', 'Info'), ('warning', 'Warning')], default='info', help_text='Status of this step', max_length=10)),
                ('message', models.CharField(blank=True, help_text='Human-readable message describing the event', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Step-specific data (totals, counts, errors, IDs, etc.)')),
                ('celery_task_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_events', to='core.celerytasklog')),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_events', to='events.emaillog')),
                ('flow', models.ForeignKey(help_text='Flow this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.platformflow')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_events', to='events.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_events', to='payment_processor.payment')),
            ],
            options={
                'verbose_name': 'Platform Flow Event',
                'verbose_name_plural': 'Platform Flow Events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['flow', 'created_at'], name='core_platfo_flow_id_9777a9_idx'), models.Index(fields=['step', 'status', 'created_at'], name='core_platfo_step_aee699_idx'), models.Index(fields=['order', 'created_at'], name='core_platfo_order_i_b0171a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='platformflow',
            index=models.Index(fields=['flow_type', 'status', 'created_at'], name='core_platfo_flow_ty_0b3096_idx'),
        ),
        migrations.AddIndex(
            model_name='platformflow',
            index=models.Index(fields=['user', 'created_at'], name='core_platfo_user_id_f3b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='platformflow',
            index=models.Index(fields=['organizer', 'created_at'], name='core_platfo_organiz_9ac7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='platformflow',
            index=models.Index(fields=['status', 'created_at'], name='core_platfo_status_819449_idx'),
        ),
        migrations.AddIndex(
            model_name='celerytasklog',
            index=models.Index(fields=['task_id'], name='core_celery_task_id_0ba4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='celerytasklog',
            index=models.Index(fields=['task_name', 'status', 'created_at'], name='core_celery_task_na_c2cb54_idx'),
        ),
        migrations.AddIndex(
            model_name='celerytasklog',
            index=models.Index(fields=['flow', 'created_at'], name='core_celery_flow_id_2c2422_idx'),
        ),
        migrations.AddIndex(
            model_name='celerytasklog',
            index=models.Index(fields=['order', 'created_at'], name='core_celery_order_i_4d70ed_idx'),
        ),
        migrations.AddIndex(
            model_name='celerytasklog',
            index=models.Index(fields=['status', 'created_at'], name='core_celery_status_44aa85_idx'),
        ),
    ]
