# Generated by Django 4.2.8 on 2025-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_platform_flow_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformflow',
            name='duration_ms',
            field=models.IntegerField(blank=True, help_text='Total duration of flow in milliseconds (for completed flows)', null=True),
        ),
        migrations.AddIndex(
            model_name='platformflow',
            index=models.Index(fields=['duration_ms'], name='core_platfo_duratio_961bfc_idx'),
        ),
    ]
