# Generated by Django 4.2.8 on 2025-12-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_duration_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformflowevent',
            name='step',
            field=models.CharField(choices=[('RESERVATION_REQUESTED', 'Reservation Requested'), ('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_EXPIRED', 'Reservation Expired'), ('ORDER_CREATED', 'Order Created'), ('ORDER_MARKED_PAID', 'Order Marked as Paid'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_REFUNDED', 'Order Refunded'), ('PAYMENT_REQUIRED', 'Payment Required'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_AUTHORIZED', 'Payment Authorized'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_CANCELLED', 'Payment Cancelled'), ('HOLDER_DATA_STORED', 'Ticket Holder Data Stored'), ('TICKETS_CREATED', 'Tickets Created'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('EMAIL_PENDING', 'Email Pending - Will Send from Frontend'), ('EMAIL_SYNC_ATTEMPT', 'Email Sync Send Attempt'), ('EMAIL_TASK_ENQUEUED', 'Email Task Enqueued'), ('EMAIL_TASK_STARTED', 'Email Task Started'), ('EMAIL_SENT', 'Email Sent Successfully'), ('EMAIL_FAILED', 'Email Failed'), ('EMAIL_MANUAL_RESEND', 'Email Manual Resend'), ('COUPON_APPLIED', 'Coupon Applied'), ('COUPON_VALIDATION_FAILED', 'Coupon Validation Failed'), ('FLOW_COMPLETED', 'Flow Completed Successfully'), ('FLOW_FAILED', 'Flow Failed'), ('FLOW_ABANDONED', 'Flow Abandoned')], db_index=True, help_text='Specific step in the flow', max_length=50),
        ),
    ]
