# Generated by Django 4.2.8 on 2025-12-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_email_sync_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(help_text="Country name (e.g., 'Chile', 'Brasil', 'Colombia')", max_length=100, unique=True, verbose_name='country name')),
                ('code', models.CharField(blank=True, help_text="ISO country code (optional, e.g., 'CHL', 'BRA')", max_length=3, null=True, unique=True, verbose_name='country code')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this country is active and can be assigned', verbose_name='active')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which countries should be displayed (lower = first)', verbose_name='display order')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order', 'name'], name='core_countr_is_acti_3973be_idx')],
            },
        ),
    ]
