# Generated by Django 4.2.8 on 2026-02-20 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_platformuptimeheartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuptimeheartbeat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='platformuptimeheartbeat',
            index=models.Index(fields=['recorded_at'], name='core_platfo_recorde_32deea_idx'),
        ),
    ]
