# Generated by Django 4.2.8 on 2026-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_platformflow_erasmus_activity_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformflowevent',
            name='step',
            field=models.CharField(choices=[('RESERVATION_REQUESTED', 'Reservation Requested'), ('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_EXPIRED', 'Reservation Expired'), ('ORDER_CREATED', 'Order Created'), ('ORDER_MARKED_PAID', 'Order Marked as Paid'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_REFUNDED', 'Order Refunded'), ('PAYMENT_REQUIRED', 'Payment Required'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_AUTHORIZED', 'Payment Authorized'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_CANCELLED', 'Payment Cancelled'), ('HOLDER_DATA_STORED', 'Ticket Holder Data Stored'), ('TICKETS_CREATED', 'Tickets Created'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('EMAIL_PENDING', 'Email Pending - Will Send from Frontend'), ('EMAIL_SYNC_ATTEMPT', 'Email Sync Send Attempt'), ('EMAIL_TASK_ENQUEUED', 'Email Task Enqueued'), ('EMAIL_TASK_STARTED', 'Email Task Started'), ('EMAIL_SENT', 'Email Sent Successfully'), ('EMAIL_FAILED', 'Email Failed'), ('EMAIL_MANUAL_RESEND', 'Email Manual Resend'), ('COUPON_APPLIED', 'Coupon Applied'), ('COUPON_VALIDATION_FAILED', 'Coupon Validation Failed'), ('FLOW_COMPLETED', 'Flow Completed Successfully'), ('FLOW_FAILED', 'Flow Failed'), ('FLOW_ABANDONED', 'Flow Abandoned'), ('ERASMUS_LINK_VISIT', 'Erasmus Link Visit'), ('ERASMUS_FORM_STARTED', 'Erasmus Form Started'), ('ERASMUS_STEP_COMPLETED', 'Erasmus Step Completed'), ('ERASMUS_FORM_SUBMITTED', 'Erasmus Form Submitted'), ('ERASMUS_FLOW_ABANDONED', 'Erasmus Flow Abandoned'), ('WHATSAPP_REQUEST_RECEIVED', 'WhatsApp Request Received'), ('OPERATOR_NOTIFIED', 'Operator Notified'), ('AVAILABILITY_CONFIRMED', 'Availability Confirmed'), ('PAYMENT_LINK_SENT', 'Payment Link Sent'), ('WHATSAPP_RESERVATION_REJECTED', 'WhatsApp Reservation Rejected'), ('CUSTOMER_MESSAGE_WAITING_SENT', 'Customer Message: Waiting (verificando disponibilidad)'), ('CUSTOMER_MESSAGE_AVAILABILITY_SENT', 'Customer Message: Availability confirmed'), ('CUSTOMER_MESSAGE_PAYMENT_LINK_SENT', 'Customer Message: Payment link'), ('CUSTOMER_MESSAGE_CONFIRM_FREE_SENT', 'Customer Message: Confirm free (responde SI)'), ('CUSTOMER_MESSAGE_CONFIRMATION_SENT', 'Customer Message: Reservation confirmed'), ('CUSTOMER_MESSAGE_REJECTION_SENT', 'Customer Message: Rejection'), ('CUSTOMER_MESSAGE_PAYMENT_SUCCESS_SENT', 'Customer Message: Payment success / comprobante'), ('WHATSAPP_MESSAGE_FAILED', 'WhatsApp Message Send Failed')], db_index=True, help_text='Specific step in the flow', max_length=50),
        ),
    ]
