# Generated by Django 4.2.8 on 2026-03-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_platformdeploy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformdeploy',
            new_name='core_platfo_deploye_950111_idx',
            old_name='core_platfo_deploye_idx',
        ),
    ]
