# Generated by Django 4.2.8 on 2026-03-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_core_platfo_deploye_idx_core_platfo_deploye_950111_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformflow',
            name='flow_type',
            field=models.CharField(choices=[('ticket_checkout', 'Ticket Checkout (Events)'), ('experience_booking', 'Experience Booking'), ('accommodation_booking', 'Accommodation Booking'), ('tour_booking', 'Tour Booking'), ('erasmus_registration', 'Erasmus Registration'), ('erasmus_activity_inscription', 'Erasmus Activity Inscription (paid)'), ('otp_login', 'OTP Login'), ('otp_organizer_login', 'OTP Login Organizador'), ('otp_password_reset', 'OTP Recuperación de contraseña'), ('otp_ticket_access', 'OTP Acceso a tickets'), ('otp_event_creation', 'OTP Creación de evento'), ('otp_email_verification', 'OTP Verificación de email'), ('otp_account_creation', 'OTP Creación de cuenta'), ('creator_application', 'Solicitud cuenta Creator/Influencer'), ('contest_registration', 'Inscripción concurso / sorteo')], db_index=True, help_text='Type of business flow being tracked', max_length=50),
        ),
    ]
