# Generated by Django 4.2.8 on 2026-03-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payableline',
            new_name='finance_pay_payee_i_9415d6_idx',
            old_name='finance_paya_payee_i_22cc68_idx',
        ),
        migrations.RenameIndex(
            model_name='payableline',
            new_name='finance_pay_payee_i_960b86_idx',
            old_name='finance_paya_payee_i_f09d4c_idx',
        ),
        migrations.RenameIndex(
            model_name='payableline',
            new_name='finance_pay_source__2c4dcf_idx',
            old_name='finance_paya_source__c30e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='payeeaccount',
            new_name='finance_pay_actor_t_3c4277_idx',
            old_name='finance_paye_actor_t_5ea214_idx',
        ),
        migrations.RenameIndex(
            model_name='payeeaccount',
            new_name='finance_pay_display_1131c8_idx',
            old_name='finance_paye_display_f7a172_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='finance_pay_payee_i_3aa8d4_idx',
            old_name='finance_payo_payee_i_b0a5e2_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='finance_pay_status_374c8a_idx',
            old_name='finance_payo_status_733161_idx',
        ),
    ]
