# Generated by Django 4.2.8 on 2026-03-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0019_add_payout_model'),
        ('finance', '0008_externalrevenuerecord_organizer_null_already_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementline',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('collection_income', 'Collection income'), ('collection_refund', 'Collection refund'), ('payout', 'Partner payout'), ('vendor_payment', 'Vendor payment'), ('transfer', 'Transfer'), ('expense', 'Expense'), ('vat', 'VAT / tax'), ('other', 'Other')], db_index=True, max_length=30, verbose_name='movement type'),
        ),
        migrations.AlterField(
            model_name='externalrevenuerecord',
            name='already_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Revenue already paid/transferred before platform (pre-platform events)', verbose_name='already paid'),
        ),
        migrations.AlterField(
            model_name='externalrevenuerecord',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='Optional for pre-platform revenue (orphan records)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_revenue_records', to='organizers.organizer'),
        ),
        migrations.AlterField(
            model_name='payableline',
            name='invoice_reference',
            field=models.CharField(blank=True, help_text='Boleta de honorarios number (required for creators before payment)', max_length=100, verbose_name='invoice reference'),
        ),
    ]
