# Generated by Django 4.2.8 on 2025-10-13 20:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre descriptivo para esta sincronización', max_length=255)),
                ('woocommerce_product_id', models.PositiveIntegerField(help_text='ID del producto/evento en WooCommerce')),
                ('event_name', models.CharField(help_text='Nombre que tendrá el evento en Django', max_length=255)),
                ('organizer_email', models.EmailField(help_text='Email del organizador (se creará si no existe)', max_length=254)),
                ('organizer_name', models.CharField(blank=True, help_text='Nombre del organizador (opcional)', max_length=255)),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje de cargo por servicio (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('frequency', models.CharField(choices=[('manual', 'Manual'), ('hourly', 'Cada hora'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='daily', help_text='Frecuencia de sincronización', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('disabled', 'Deshabilitado'), ('error', 'Error')], default='active', help_text='Estado de la sincronización', max_length=20)),
                ('event_description', models.TextField(blank=True, help_text='Descripción del evento (opcional)')),
                ('event_start_date', models.DateTimeField(blank=True, help_text='Fecha de inicio del evento (opcional)', null=True)),
                ('event_end_date', models.DateTimeField(blank=True, help_text='Fecha de fin del evento (opcional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Última vez que se ejecutó la sincronización', null=True)),
                ('last_sync_status', models.CharField(blank=True, help_text='Estado de la última sincronización', max_length=20)),
                ('total_syncs', models.PositiveIntegerField(default=0, help_text='Número total de sincronizaciones ejecutadas')),
                ('successful_syncs', models.PositiveIntegerField(default=0, help_text='Número de sincronizaciones exitosas')),
                ('django_event_id', models.UUIDField(blank=True, help_text='ID del evento creado en Django', null=True)),
                ('django_organizer_id', models.UUIDField(blank=True, help_text='ID del organizador en Django', null=True)),
                ('django_form_id', models.UUIDField(blank=True, help_text='ID del formulario creado en Django', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_configurations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Sincronización',
                'verbose_name_plural': 'Configuraciones de Sincronización',
                'ordering': ['-created_at'],
                'unique_together': {('woocommerce_product_id', 'organizer_email')},
            },
        ),
        migrations.CreateModel(
            name='SyncCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para estas credenciales', max_length=255, unique=True)),
                ('ssh_host', models.CharField(max_length=255)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('ssh_username', models.CharField(max_length=255)),
                ('mysql_host', models.CharField(default='localhost', max_length=255)),
                ('mysql_port', models.PositiveIntegerField(default=3306)),
                ('mysql_database', models.CharField(max_length=255)),
                ('mysql_username', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credenciales de Sincronización',
                'verbose_name_plural': 'Credenciales de Sincronización',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyncExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutándose'), ('success', 'Exitoso'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('scheduled', 'Programado'), ('manual', 'Manual'), ('api', 'API'), ('retry', 'Reintento')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('orders_processed', models.PositiveIntegerField(default=0)),
                ('tickets_processed', models.PositiveIntegerField(default=0)),
                ('orders_created', models.PositiveIntegerField(default=0)),
                ('orders_updated', models.PositiveIntegerField(default=0)),
                ('tickets_created', models.PositiveIntegerField(default=0)),
                ('tickets_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la sincronización falló')),
                ('celery_task_id', models.CharField(blank=True, help_text='ID de la tarea de Celery', max_length=255)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='sync_woocommerce.syncconfiguration')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Usuario que disparó la sincronización (si fue manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de Sincronización',
                'verbose_name_plural': 'Ejecuciones de Sincronización',
                'ordering': ['-started_at'],
            },
        ),
    ]
