# Generated by Django 4.2.8 on 2025-10-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_woocommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncexecution',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID de la tarea de Celery', max_length=255, null=True),
        ),
    ]
