# Generated by Django 4.2.8 on 2025-10-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_woocommerce', '0002_alter_syncexecution_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncconfiguration',
            name='ticket_tier_name',
            field=models.CharField(default='General', help_text='Nombre del TicketTier que se creará', max_length=255),
        ),
    ]
