# Generated by Django 4.2.8 on 2026-02-18 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0005_rental_hub_and_blocked_dates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accommodationblockeddate',
            new_name='accommodati_accommo_cf3127_idx',
            old_name='accommodati_accommo_6b0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='accommodationreservation',
            new_name='accommodati_reserva_1970f8_idx',
            old_name='accommodati_reserva_6a0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='accommodationreservation',
            new_name='accommodati_accommo_15de3a_idx',
            old_name='accommodati_accommo_8b2c1e_idx',
        ),
        migrations.RenameIndex(
            model_name='accommodationreservation',
            new_name='accommodati_check_i_cf9b6b_idx',
            old_name='accommodati_check_i_9d3f2a_idx',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='amenities',
            field=models.JSONField(default=list, help_text="List of amenity strings, e.g. ['WiFi', 'Cocina', 'Parrilla']", verbose_name='amenities'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='gallery_items',
            field=models.JSONField(blank=True, default=list, help_text='List of {media_id, room_category, sort_order, is_principal}. sort_order = global order in gallery; is_principal = image for cards/listings. room_category from ROOM_CATEGORIES or null. gallery_media_ids synced on save.', verbose_name='gallery items with order and room category'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='gallery_media_ids',
            field=models.JSONField(default=list, help_text='UUIDs of MediaAsset for gallery (optional)', verbose_name='gallery media asset IDs'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='not_amenities',
            field=models.JSONField(default=list, help_text="List of things not available, e.g. ['TV', 'Lavadora']", verbose_name='not available'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio por noche mostrado al huésped. Plataforma retiene 20%; anfitrión recibe 80%.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price per night (guest-facing)'),
        ),
        migrations.AlterField(
            model_name='accommodationblockeddate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='accommodationreview',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rentalhub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='rentalhub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
