# Generated by Django 4.2.8 on 2026-02-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0007_create_playa_blanca_rental_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='tower',
            field=models.CharField(blank=True, db_index=True, help_text='Torre o bloque (ej. A, B). Depende de la central.', max_length=30, verbose_name='tower'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='unit_type',
            field=models.CharField(blank=True, db_index=True, help_text='Código de tipo de unidad según la central (ej. A1, A2, B, C en Playa Blanca; Estudio, 1D en otra).', max_length=30, verbose_name='unit type'),
        ),
    ]
