# Generated by Django 4.2.8 on 2026-03-05 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0013_min_nights_rental_hub_hotel_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='payment_model',
            field=models.CharField(blank=True, choices=[('full_platform', 'Full platform (guest pays total online)'), ('commission_only', 'Commission only (guest pays commission online, rest at property)')], default='', help_text='If blank and hotel_id set, inherits from hotel. Otherwise platform default.', max_length=20, verbose_name='payment model'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='tuki_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Platform commission e.g. 0.20 = 20%%. Room overrides hotel; null = inherit or default.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Tuki commission rate'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='payment_model',
            field=models.CharField(blank=True, choices=[('full_platform', 'Full platform (guest pays total online; Tuki retains commission)'), ('commission_only', 'Commission only (guest pays Tuki commission online; rest at hotel)')], default='full_platform', help_text='full_platform: guest pays total online. commission_only: guest pays commission online, rest at hotel.', max_length=20, verbose_name='payment model'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tuki_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Platform commission rate e.g. 0.20 = 20%%. Null = use platform default.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Tuki commission rate'),
        ),
    ]
