# Generated by Django 4.2.8 on 2026-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0015_whatsapp_message_templates_rental_hub_hotel_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='whatsapp_message_templates',
            field=models.JSONField(blank=True, default=dict, help_text='Optional overrides for reservation flow messages (room/unit level). Wins over hotel/central and platform. Keys: reservation_request, customer_waiting, etc.', verbose_name='WhatsApp reservation message templates'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='whatsapp_message_templates',
            field=models.JSONField(blank=True, default=dict, help_text='Optional overrides for reservation flow messages (hotel level). Rooms inherit; room override wins. Keys: reservation_request, customer_waiting, etc.', verbose_name='WhatsApp reservation message templates'),
        ),
    ]
