# Generated by Django 4.2.8 on 2026-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0018_accommodation_extra_charge_and_pricing_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationextracharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='accommodationextracharge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
