# Generated by Django 4.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0019_alter_accommodationextracharge_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhub',
            name='units_section_title',
            field=models.CharField(
                blank=True,
                default='Nuestros Departamentos',
                help_text="Title of the units list section on the hub landing (e.g. 'Nuestros Departamentos', 'Nuestras Casas').",
                max_length=255,
                verbose_name='units section title',
            ),
        ),
        migrations.AddField(
            model_name='rentalhub',
            name='units_section_subtitle',
            field=models.CharField(
                blank=True,
                default='Selecciona la unidad perfecta para tu estadía',
                help_text='Subtitle below the units section title on the hub landing.',
                max_length=500,
                verbose_name='units section subtitle',
            ),
        ),
    ]
