# Generated by Django 4.2.8
# Replaces single "bathrooms" with industry-standard full_bathrooms (toilet+sink+shower)
# and half_bathrooms (toilet+sink only; powder room).

from django.db import migrations, models
import django.core.validators


def backfill_bathrooms(apps, schema_editor):
    Accommodation = apps.get_model("accommodations", "Accommodation")
    for acc in Accommodation.objects.all():
        acc.full_bathrooms = getattr(acc, "bathrooms", 1) or 1
        acc.half_bathrooms = 0
        acc.save(update_fields=["full_bathrooms", "half_bathrooms"])


def reverse_backfill(apps, schema_editor):
    Accommodation = apps.get_model("accommodations", "Accommodation")
    for acc in Accommodation.objects.all():
        acc.bathrooms = (acc.full_bathrooms or 0) + (acc.half_bathrooms or 0)
        acc.save(update_fields=["bathrooms"])


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0020_rentalhub_units_section_title_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="full_bathrooms",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Full bathrooms: toilet, sink, and shower or bathtub.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="full bathrooms",
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="half_bathrooms",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Half bathrooms (powder rooms): toilet and sink only, no shower.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="half bathrooms",
            ),
        ),
        migrations.RunPython(backfill_bathrooms, reverse_backfill),
        migrations.RemoveField(
            model_name="accommodation",
            name="bathrooms",
        ),
    ]
