# Generated by Django 4.2.8 on 2026-01-05 13:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalCompany',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Company name (case-insensitive unique)', max_length=255, unique=True, verbose_name='name')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True, verbose_name='email')),
                ('website', models.URLField(blank=True, help_text='Company website URL', null=True, verbose_name='website')),
                ('logo', models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='terminal/companies/logos/', verbose_name='logo')),
                ('contact_method', models.CharField(choices=[('internal', 'Internal (Tuki platform)'), ('whatsapp', 'WhatsApp'), ('external', 'External website')], default='external', help_text='Default contact method', max_length=20, verbose_name='contact method')),
                ('booking_url', models.URLField(blank=True, help_text='Direct booking link', null=True, verbose_name='booking URL')),
                ('booking_phone', models.CharField(blank=True, help_text='Phone number for reservations', max_length=20, null=True, verbose_name='booking phone')),
                ('booking_whatsapp', models.CharField(blank=True, help_text='WhatsApp number for reservations (e.g., +56912345678)', max_length=20, null=True, verbose_name='booking WhatsApp')),
                ('booking_method', models.CharField(choices=[('internal', 'Internal (Tuki platform)'), ('external', 'External website'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone call')], default='external', help_text='Method used for reservations', max_length=20, verbose_name='booking method')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this company is active', verbose_name='active')),
            ],
            options={
                'verbose_name': 'Terminal Company',
                'verbose_name_plural': 'Terminal Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TerminalExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255, verbose_name='file name')),
                ('file_path', models.FileField(help_text='Uploaded Excel file', upload_to='terminal/uploads/', verbose_name='file')),
                ('upload_type', models.CharField(choices=[('departures', 'Departures'), ('arrivals', 'Arrivals')], help_text='Whether this is departures or arrivals', max_length=20, verbose_name='upload type')),
                ('date_range_start', models.DateField(help_text='Start date of the schedule range', verbose_name='date range start')),
                ('date_range_end', models.DateField(help_text='End date of the schedule range', verbose_name='date range end')),
                ('processed_sheets', models.JSONField(blank=True, default=list, help_text='List of sheet names that were processed', verbose_name='processed sheets')),
                ('trips_created', models.IntegerField(default=0, help_text='Number of trips created', verbose_name='trips created')),
                ('trips_updated', models.IntegerField(default=0, help_text='Number of trips updated', verbose_name='trips updated')),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of errors encountered during processing', verbose_name='errors')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Processing status', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Terminal Excel Upload',
                'verbose_name_plural': 'Terminal Excel Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalRoute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(db_index=True, help_text='Origin city/location', max_length=255, verbose_name='origin')),
                ('destination', models.CharField(db_index=True, help_text='Destination city/location', max_length=255, verbose_name='destination')),
                ('duration', models.CharField(blank=True, help_text='Approximate duration (e.g., "1h 30min")', max_length=50, null=True, verbose_name='duration')),
                ('distance', models.CharField(blank=True, help_text='Distance (e.g., "65 km")', max_length=50, null=True, verbose_name='distance')),
            ],
            options={
                'verbose_name': 'Terminal Route',
                'verbose_name_plural': 'Terminal Routes',
            },
        ),
        migrations.CreateModel(
            name='TerminalTrip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_type', models.CharField(choices=[('departure', 'Departure (from terminal)'), ('arrival', 'Arrival (to terminal)')], db_index=True, help_text='Whether this is a departure or arrival', max_length=20, verbose_name='trip type')),
                ('date', models.DateField(db_index=True, help_text='Trip date', verbose_name='date')),
                ('departure_time', models.TimeField(blank=True, help_text='Departure time (only for departures)', null=True, verbose_name='departure time')),
                ('arrival_time', models.TimeField(blank=True, help_text='Arrival time (only for arrivals)', null=True, verbose_name='arrival time')),
                ('platform', models.CharField(blank=True, help_text='Platform number (andén)', max_length=10, null=True, verbose_name='platform')),
                ('license_plate', models.CharField(blank=True, help_text='Bus license plate (placa)', max_length=20, null=True, verbose_name='license plate')),
                ('observations', models.TextField(blank=True, help_text='Additional observations', null=True, verbose_name='observations')),
                ('total_seats', models.IntegerField(blank=True, help_text='Total seats (NULL in v1, not shown in UI)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total seats')),
                ('available_seats', models.IntegerField(blank=True, help_text='Available seats (NULL in v1, not shown in UI)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='available seats')),
                ('status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited availability'), ('sold_out', 'Sold out')], db_index=True, default='available', help_text='Trip availability status', max_length=20, verbose_name='status')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Ticket price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price')),
                ('currency', models.CharField(default='CLP', help_text='Currency code (e.g., CLP)', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='If False, hidden from public searches', verbose_name='active')),
                ('company', models.ForeignKey(help_text='Bus company operating this trip', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='terminal.terminalcompany', verbose_name='company')),
                ('route', models.ForeignKey(help_text='Route for this trip', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='terminal.terminalroute', verbose_name='route')),
            ],
            options={
                'verbose_name': 'Terminal Trip',
                'verbose_name_plural': 'Terminal Trips',
                'ordering': ['date', 'departure_time', 'arrival_time'],
            },
        ),
        migrations.AddIndex(
            model_name='terminalroute',
            index=models.Index(fields=['origin', 'destination'], name='terminal_te_origin_96890b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terminalroute',
            unique_together={('origin', 'destination')},
        ),
        migrations.AddField(
            model_name='terminalexcelupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_uploads', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.AddIndex(
            model_name='terminalcompany',
            index=models.Index(fields=['name'], name='terminal_te_name_dea512_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalcompany',
            index=models.Index(fields=['is_active'], name='terminal_te_is_acti_c815c0_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaltrip',
            index=models.Index(fields=['date', 'trip_type', 'is_active'], name='terminal_te_date_88d756_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaltrip',
            index=models.Index(fields=['company', 'date'], name='terminal_te_company_bc90ad_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaltrip',
            index=models.Index(fields=['route', 'date'], name='terminal_te_route_i_fbfe5d_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaltrip',
            index=models.Index(fields=['status', 'is_active'], name='terminal_te_status_f52cb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terminaltrip',
            unique_together={('company', 'route', 'date', 'trip_type', 'departure_time', 'arrival_time')},
        ),
        migrations.AddIndex(
            model_name='terminalexcelupload',
            index=models.Index(fields=['status', 'created_at'], name='terminal_te_status_dae794_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalexcelupload',
            index=models.Index(fields=['upload_type', 'created_at'], name='terminal_te_upload__12e4a7_idx'),
        ),
    ]
