# Generated by Django 4.2.8 on 2026-01-15 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0009_studentcentertimelineitem_studentinterest_and_more'),
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalAdvertisingInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('impression', 'Impression')], db_index=True, help_text='Type of interaction', max_length=20, verbose_name='interaction type')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='User IP address', null=True, verbose_name='user ip')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True, verbose_name='user agent')),
                ('referrer', models.URLField(blank=True, help_text='Referrer URL', null=True, verbose_name='referrer')),
                ('destination', models.CharField(blank=True, help_text='Destination from which the interaction occurred', max_length=255, null=True, verbose_name='destination')),
            ],
            options={
                'verbose_name': 'Terminal Advertising Interaction',
                'verbose_name_plural': 'Terminal Advertising Interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalAdvertisingSpace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('space_type', models.CharField(choices=[('hero_slider', 'Hero Slider'), ('featured_experiences', 'Featured Experiences'), ('destination_banner', 'Destination Banner'), ('experience_card', 'Experience Card')], db_index=True, help_text='Type of advertising space', max_length=50, verbose_name='space type')),
                ('position', models.CharField(db_index=True, help_text='Unique position identifier (e.g., "home_featured_1", "destination_chaiten_banner")', max_length=255, verbose_name='position')),
                ('route_origin', models.CharField(blank=True, db_index=True, help_text='Origin of route (e.g., "Coyhaique")', max_length=255, null=True, verbose_name='route origin')),
                ('route_destination', models.CharField(blank=True, db_index=True, help_text='Destination of route (e.g., "Chaitén")', max_length=255, null=True, verbose_name='route destination')),
                ('content_type', models.CharField(choices=[('experience', 'Experience'), ('banner', 'Banner'), ('custom', 'Custom')], help_text='Type of content: experience, banner, or custom', max_length=20, verbose_name='content type')),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image (if content_type is "banner")', null=True, upload_to='terminal/advertising/banners/', verbose_name='banner image')),
                ('banner_title', models.CharField(blank=True, help_text='Banner title', max_length=255, null=True, verbose_name='banner title')),
                ('banner_subtitle', models.CharField(blank=True, help_text='Banner subtitle', max_length=500, null=True, verbose_name='banner subtitle')),
                ('banner_cta_text', models.CharField(blank=True, help_text='Banner call-to-action text', max_length=100, null=True, verbose_name='banner cta text')),
                ('banner_cta_url', models.URLField(blank=True, help_text='Banner call-to-action URL', null=True, verbose_name='banner cta url')),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Display order', verbose_name='order')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this space is active', verbose_name='active')),
                ('display_from', models.DateTimeField(blank=True, db_index=True, help_text='Start date/time for display', null=True, verbose_name='display from')),
                ('display_until', models.DateTimeField(blank=True, db_index=True, help_text='End date/time for display', null=True, verbose_name='display until')),
            ],
            options={
                'verbose_name': 'Terminal Advertising Space',
                'verbose_name_plural': 'Terminal Advertising Spaces',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalDestination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Destination name (unique)', max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, help_text='Destination description', null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, help_text='Destination image', null=True, upload_to='terminal/destinations/', verbose_name='image')),
                ('region', models.CharField(blank=True, help_text='Region name (e.g., "Aysén")', max_length=255, null=True, verbose_name='region')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this destination is active', verbose_name='active')),
                ('created_from_excel', models.BooleanField(default=False, help_text='Indicates if this destination was created automatically from Excel upload', verbose_name='created from excel')),
            ],
            options={
                'verbose_name': 'Terminal Destination',
                'verbose_name_plural': 'Terminal Destinations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TerminalDestinationExperienceConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Whether this experience appears in featured section', verbose_name='is featured')),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Display order for featured experiences', verbose_name='order')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this configuration is active', verbose_name='active')),
                ('destination', models.ForeignKey(help_text='Destination this configuration applies to', on_delete=django.db.models.deletion.CASCADE, related_name='experience_configs', to='terminal.terminaldestination', verbose_name='destination')),
                ('experience', models.ForeignKey(help_text='Experience to display for this destination', on_delete=django.db.models.deletion.CASCADE, related_name='terminal_destination_configs', to='experiences.experience', verbose_name='experience')),
            ],
            options={
                'verbose_name': 'Terminal Destination Experience Config',
                'verbose_name_plural': 'Terminal Destination Experience Configs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='terminaldestination',
            index=models.Index(fields=['name'], name='terminal_te_name_d3520e_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaldestination',
            index=models.Index(fields=['slug'], name='terminal_te_slug_5f3a74_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaldestination',
            index=models.Index(fields=['is_active'], name='terminal_te_is_acti_344a15_idx'),
        ),
        migrations.AddField(
            model_name='terminaladvertisingspace',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Destination this space applies to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertising_spaces', to='terminal.terminaldestination', verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='terminaladvertisingspace',
            name='experience',
            field=models.ForeignKey(blank=True, help_text='Experience to display (if content_type is "experience")', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_advertising_spaces', to='experiences.experience', verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='terminaladvertisinginteraction',
            name='advertising_space',
            field=models.ForeignKey(help_text='The advertising space that was interacted with', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='terminal.terminaladvertisingspace', verbose_name='advertising space'),
        ),
        migrations.AddIndex(
            model_name='terminaldestinationexperienceconfig',
            index=models.Index(fields=['destination', 'is_featured', 'is_active'], name='terminal_te_destina_252dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaldestinationexperienceconfig',
            index=models.Index(fields=['is_featured', 'order'], name='terminal_te_is_feat_701966_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terminaldestinationexperienceconfig',
            unique_together={('destination', 'experience')},
        ),
        migrations.AddIndex(
            model_name='terminaladvertisingspace',
            index=models.Index(fields=['space_type', 'is_active'], name='terminal_te_space_t_6c6693_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaladvertisingspace',
            index=models.Index(fields=['destination', 'is_active'], name='terminal_te_destina_58670e_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaladvertisingspace',
            index=models.Index(fields=['position'], name='terminal_te_positio_9fac69_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaladvertisingspace',
            index=models.Index(fields=['display_from', 'display_until'], name='terminal_te_display_500d39_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaladvertisinginteraction',
            index=models.Index(fields=['advertising_space', 'interaction_type'], name='terminal_te_adverti_6d21fd_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaladvertisinginteraction',
            index=models.Index(fields=['interaction_type', 'created_at'], name='terminal_te_interac_7f61fc_idx'),
        ),
        migrations.AddIndex(
            model_name='terminaladvertisinginteraction',
            index=models.Index(fields=['created_at'], name='terminal_te_created_8551e8_idx'),
        ),
    ]
