# Generated by Django 4.2.8 on 2025-12-31 12:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0008_change_country_to_foreignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceOperatorBinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0, help_text='Lower number = higher priority', verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Experience-Operator Binding',
                'verbose_name_plural': 'Experience-Operator Bindings',
                'ordering': ['experience', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TourOperator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Contact Name')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number for receiving notifications (e.g., 56912345678)', max_length=20, verbose_name='WhatsApp Number')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Tour Operator',
                'verbose_name_plural': 'Tour Operators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whatsapp_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='WhatsApp ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Phone')),
                ('type', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3, verbose_name='Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('processed', models.BooleanField(db_index=True, default=False, verbose_name='Processed')),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('qr_pending', 'Esperando QR'), ('connected', 'Conectado'), ('expired', 'Expirado')], default='disconnected', max_length=20, verbose_name='Status')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Last Seen')),
                ('qr_code', models.TextField(blank=True, help_text='Base64 QR code for authentication', verbose_name='QR Code')),
            ],
            options={
                'verbose_name': 'WhatsApp Session',
                'verbose_name_plural': 'WhatsApp Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppReservationRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tour_code', models.CharField(db_index=True, max_length=50, verbose_name='Tour Code')),
                ('passengers', models.IntegerField(blank=True, null=True, verbose_name='Passengers')),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('operator_notified', 'Operador notificado'), ('confirmed', 'Confirmada'), ('rejected', 'Rechazada'), ('timeout', 'Timeout')], db_index=True, default='received', max_length=20, verbose_name='Status')),
                ('timeout_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Timeout At')),
                ('confirmation_token', models.CharField(blank=True, help_text='Token for operator confirmation', max_length=10, verbose_name='Confirmation Token')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_reservations', to='experiences.experience', verbose_name='Experience')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_requests', to='whatsapp.touroperator', verbose_name='Operator')),
                ('whatsapp_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='whatsapp.whatsappmessage', verbose_name='WhatsApp Message')),
            ],
            options={
                'verbose_name': 'WhatsApp Reservation Request',
                'verbose_name_plural': 'WhatsApp Reservation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['phone', 'processed'], name='whatsapp_wh_phone_65148f_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['whatsapp_id'], name='whatsapp_wh_whatsap_b03d3d_idx'),
        ),
        migrations.AddField(
            model_name='experienceoperatorbinding',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_bindings', to='experiences.experience', verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='experienceoperatorbinding',
            name='tour_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_bindings', to='whatsapp.touroperator', verbose_name='Tour Operator'),
        ),
        migrations.AddIndex(
            model_name='whatsappreservationrequest',
            index=models.Index(fields=['status', 'timeout_at'], name='whatsapp_wh_status_d56469_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappreservationrequest',
            index=models.Index(fields=['tour_code', 'status'], name='whatsapp_wh_tour_co_d7cd04_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='experienceoperatorbinding',
            unique_together={('experience', 'tour_operator')},
        ),
    ]
