# Generated by Django 4.2.8 on 2025-12-31 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_change_country_to_foreignkey'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppChat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Chat ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Grupo')], db_index=True, max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Message At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'WhatsApp Chat',
                'verbose_name_plural': 'WhatsApp Chats',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppReservationCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code')),
                ('checkout_data', models.JSONField(default=dict, help_text='Participants, date, time, pricing, etc.', verbose_name='Checkout Data')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('linked', 'Vinculado'), ('expired', 'Expirado')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'WhatsApp Reservation Code',
                'verbose_name_plural': 'WhatsApp Reservation Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_reservation_related',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Is Reservation Related'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='linked_reservation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_messages', to='whatsapp.whatsappreservationrequest', verbose_name='Linked Reservation Request'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='reservation_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Reservation Code'),
        ),
        migrations.AddField(
            model_name='whatsappreservationrequest',
            name='linked_experience_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_requests', to='experiences.experiencereservation', verbose_name='Linked Experience Reservation'),
        ),
        migrations.AlterField(
            model_name='whatsappreservationrequest',
            name='passengers',
            field=models.IntegerField(blank=True, db_column='num_passengers', null=True, verbose_name='Passengers'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['reservation_code'], name='whatsapp_wh_reserva_891291_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['is_reservation_related'], name='whatsapp_wh_is_rese_af59b4_idx'),
        ),
        migrations.AddField(
            model_name='whatsappreservationcode',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_reservation_codes', to='experiences.experience', verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='whatsappreservationcode',
            name='linked_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_code', to='whatsapp.whatsappreservationrequest', verbose_name='Linked Reservation'),
        ),
        migrations.AddField(
            model_name='whatsappchat',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to='whatsapp.touroperator', verbose_name='Assigned Operator'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.whatsappchat', verbose_name='Chat'),
        ),
        migrations.AddIndex(
            model_name='whatsappreservationcode',
            index=models.Index(fields=['code', 'status'], name='whatsapp_wh_code_a41cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappreservationcode',
            index=models.Index(fields=['expires_at', 'status'], name='whatsapp_wh_expires_fb7f87_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappchat',
            index=models.Index(fields=['type', 'is_active'], name='whatsapp_wh_type_3cf307_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappchat',
            index=models.Index(fields=['assigned_operator', 'is_active'], name='whatsapp_wh_assigne_ff08e0_idx'),
        ),
    ]
