# Generated by Django 4.2.8 on 2025-12-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappchat_whatsappreservationcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappreservationrequest',
            name='passengers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Passengers'),
        ),
    ]
