# Generated by Django 4.2.8 on 2025-12-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_alter_whatsappreservationrequest_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_automated',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if this message was sent automatically by the system/AI', verbose_name='Is Automated'),
        ),
    ]
