# Generated by Django 4.2.8 on 2025-12-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_whatsappmessage_is_automated'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchat',
            name='nickname',
            field=models.CharField(blank=True, help_text='Apodo personalizado para identificar el chat', max_length=255, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='whatsappchat',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas sobre el chat/cliente', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='whatsappchat',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='URL de la foto de perfil del contacto', verbose_name='Profile Picture URL'),
        ),
        migrations.AddField(
            model_name='whatsappchat',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Lista de tags/etiquetas para categorizar el chat', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='whatsappchat',
            name='unread_count',
            field=models.IntegerField(db_index=True, default=0, help_text='Número de mensajes sin leer', verbose_name='Unread Count'),
        ),
        migrations.AddField(
            model_name='whatsappchat',
            name='whatsapp_name',
            field=models.CharField(blank=True, help_text='Nombre real del contacto en WhatsApp', max_length=255, verbose_name='WhatsApp Name'),
        ),
    ]
