# Generated by Django 4.2.8 on 2026-01-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_whatsappchat_nickname_whatsappchat_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchat',
            name='group_description',
            field=models.TextField(blank=True, help_text='Descripción del grupo (solo para grupos)', verbose_name='Group Description'),
        ),
        migrations.AddField(
            model_name='whatsappchat',
            name='participants',
            field=models.JSONField(blank=True, default=list, help_text='Lista de participantes del grupo (solo para grupos)', verbose_name='Participants'),
        ),
    ]
