# Generated by Django 4.2.8 on 2026-01-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_whatsappchat_group_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for the message (e.g., sender_name, sender_phone for group messages)', verbose_name='Metadata'),
        ),
    ]
