# Generated by Django 4.2.8 on 2026-01-02 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0014_alter_organizer_experience_dashboard_template'),
        ('experiences', '0008_change_country_to_foreignkey'),
        ('whatsapp', '0007_whatsappmessage_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroperator',
            name='default_whatsapp_group',
            field=models.ForeignKey(blank=True, help_text='Default WhatsApp group for this operator. New experiences will be linked to this group by default.', limit_choices_to={'type': 'group'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_operators', to='whatsapp.whatsappchat', verbose_name='Default WhatsApp Group'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='is_system_created',
            field=models.BooleanField(default=False, help_text='If True, operator was auto-created from Organizer when first experience was created', verbose_name='System Created'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='Organizer that owns this operator (if auto-created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_operators', to='organizers.organizer', verbose_name='Organizer'),
        ),
        migrations.CreateModel(
            name='ExperienceGroupBinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='If False, this binding is disabled and will use operator default group', verbose_name='Active')),
                ('is_override', models.BooleanField(default=False, help_text='If True, this binding overrides the operator default group', verbose_name='Override Default')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_group_bindings', to='experiences.experience', verbose_name='Experience')),
                ('tour_operator', models.ForeignKey(blank=True, help_text='Optional: operator associated with this binding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_group_bindings', to='whatsapp.touroperator', verbose_name='Tour Operator')),
                ('whatsapp_group', models.ForeignKey(blank=True, help_text='WhatsApp group where reservation requests for this experience will be sent', limit_choices_to={'type': 'group'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_bindings', to='whatsapp.whatsappchat', verbose_name='WhatsApp Group')),
            ],
            options={
                'verbose_name': 'Experience-Group Binding',
                'verbose_name_plural': 'Experience-Group Bindings',
                'indexes': [models.Index(fields=['experience', 'is_active'], name='whatsapp_ex_experie_f8d58e_idx'), models.Index(fields=['whatsapp_group', 'is_active'], name='whatsapp_ex_whatsap_9f24f8_idx')],
                'unique_together': {('experience', 'whatsapp_group')},
            },
        ),
    ]
