# Generated by Django 4.2.8 on 2026-02-02 17:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_touroperator_default_whatsapp_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappreservationrequest',
            name='customer_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional customer data collected during conversation', verbose_name='Customer Data'),
        ),
        migrations.AddField(
            model_name='whatsappreservationrequest',
            name='customer_notified_at',
            field=models.DateTimeField(blank=True, help_text='When customer was notified of result', null=True, verbose_name='Customer Notified At'),
        ),
        migrations.AddField(
            model_name='whatsappreservationrequest',
            name='operator_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Operator Responded At'),
        ),
        migrations.AddField(
            model_name='whatsappreservationrequest',
            name='operator_response',
            field=models.CharField(blank=True, help_text='Last response from operator', max_length=255, verbose_name='Operator Response'),
        ),
        migrations.AddField(
            model_name='whatsappreservationrequest',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Generated payment link sent to customer', verbose_name='Payment Link'),
        ),
        migrations.AddField(
            model_name='whatsappreservationrequest',
            name='payment_link_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Link Sent At'),
        ),
        migrations.AddField(
            model_name='whatsappreservationrequest',
            name='payment_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Received At'),
        ),
        migrations.AddField(
            model_name='whatsappreservationrequest',
            name='ticket_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Sent At'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='phone',
            field=models.CharField(db_index=True, help_text='Phone number or group ID (format: XXXXXXXXXXX-XXXXXXXXXX for groups)', max_length=50, verbose_name='Phone'),
        ),
        migrations.CreateModel(
            name='OperatorRequiredFields',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='Internal field identifier (e.g., "rut", "full_name")', max_length=50, verbose_name='Field Name')),
                ('display_name', models.CharField(help_text='Name shown to customer (e.g., "RUT", "Nombre completo")', max_length=100, verbose_name='Display Name')),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('email', 'Email'), ('phone', 'Teléfono'), ('rut', 'RUT/Identificación'), ('date', 'Fecha'), ('select', 'Selección')], default='text', max_length=20, verbose_name='Field Type')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required')),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select fields', verbose_name='Options')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_fields', to='whatsapp.touroperator', verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Operator Required Field',
                'verbose_name_plural': 'Operator Required Fields',
                'ordering': ['operator', 'order'],
                'unique_together': {('operator', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='OperatorMessageTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('reservation_request', 'Solicitud de reserva al operador'), ('customer_confirmation', 'Confirmación al cliente'), ('customer_rejection', 'Rechazo al cliente'), ('customer_waiting', 'Esperando confirmación del operador'), ('payment_link', 'Link de pago al cliente'), ('payment_confirmed', 'Pago confirmado al cliente'), ('ticket_info', 'Información del ticket'), ('reminder', 'Recordatorio al operador')], db_index=True, max_length=30, verbose_name='Message Type')),
                ('template', models.TextField(help_text='Use {{variable}} for dynamic content', verbose_name='Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='whatsapp.touroperator', verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Operator Message Template',
                'verbose_name_plural': 'Operator Message Templates',
                'ordering': ['operator', 'message_type'],
                'unique_together': {('operator', 'message_type')},
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('idle', 'Inactivo'), ('awaiting_reservation_code', 'Esperando código de reserva'), ('awaiting_customer_info', 'Esperando información del cliente'), ('awaiting_operator_response', 'Esperando respuesta del operador'), ('awaiting_payment', 'Esperando pago'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_index=True, default='idle', max_length=30, verbose_name='State')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Additional context data for the conversation', verbose_name='Context')),
                ('pending_fields', models.JSONField(blank=True, default=list, help_text='List of required fields still pending', verbose_name='Pending Fields')),
                ('collected_data', models.JSONField(blank=True, default=dict, help_text='Data collected from customer during conversation', verbose_name='Collected Data')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expires At')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_state', to='whatsapp.whatsappchat', verbose_name='Chat')),
                ('current_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_states', to='whatsapp.whatsappreservationrequest', verbose_name='Current Reservation')),
            ],
            options={
                'verbose_name': 'Conversation State',
                'verbose_name_plural': 'Conversation States',
                'indexes': [models.Index(fields=['state', 'expires_at'], name='whatsapp_co_state_314f60_idx')],
            },
        ),
    ]
