# Generated by Django 4.2.8 on 2026-02-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_increase_phone_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappreservationrequest',
            name='status',
            field=models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('operator_notified', 'Operador notificado'), ('availability_confirmed', 'Disponibilidad confirmada'), ('confirmed', 'Confirmada'), ('rejected', 'Rechazada'), ('timeout', 'Timeout')], db_index=True, default='received', max_length=30, verbose_name='Status'),
        ),
    ]
