# Generated by Django 4.2.8 on 2026-02-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_add_availability_confirmed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_type',
            field=models.CharField(blank=True, db_index=True, help_text='WhatsApp message type: chat, ptt, audio, image, video, document, sticker, etc.', max_length=30, null=True, verbose_name='Media Type'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL to media file if uploaded to storage', max_length=2048, null=True, verbose_name='Media URL'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='reply_to_whatsapp_id',
            field=models.CharField(blank=True, db_index=True, help_text='WhatsApp ID of the message this is a reply to', max_length=100, null=True, verbose_name='Reply To WhatsApp ID'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['reply_to_whatsapp_id'], name='whatsapp_wh_reply_t_20f0c2_idx'),
        ),
    ]
