# Generated by Django 4.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_add_media_and_reply_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappreservationrequest',
            name='operator',
            field=models.ForeignKey(
                blank=True,
                help_text='Nullable when experience has no operator; assign manually later',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reservation_requests',
                to='whatsapp.touroperator',
                verbose_name='Operator'
            ),
        ),
        migrations.AddField(
            model_name='whatsappchat',
            name='last_message_preview',
            field=models.CharField(
                blank=True,
                help_text='Preview of last message for chat list (without opening)',
                max_length=255,
                verbose_name='Last Message Preview'
            ),
        ),
    ]
