# Generated by Django 4.2.8 on 2026-02-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0006_rename_accommodati_accommo_6b0b0d_idx_accommodati_accommo_cf3127_idx_and_more'),
        ('whatsapp', '0015_add_flow_to_whatsapp_reservation_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accommodationgroupbinding',
            name='whatsapp_accommodationgroup_accommo_unique',
        ),
        migrations.RemoveConstraint(
            model_name='accommodationoperatorbinding',
            name='whatsapp_accommodationoperator_accommo_unique',
        ),
        migrations.RenameIndex(
            model_name='accommodationgroupbinding',
            new_name='whatsapp_ac_accommo_1ea7ab_idx',
            old_name='whatsapp_accommodati_accommo_idx',
        ),
        migrations.RenameIndex(
            model_name='accommodationgroupbinding',
            new_name='whatsapp_ac_whatsap_a5e9e1_idx',
            old_name='whatsapp_accommodati_whatsap_idx',
        ),
        migrations.AlterUniqueTogether(
            name='accommodationgroupbinding',
            unique_together={('accommodation', 'whatsapp_group')},
        ),
        migrations.AlterUniqueTogether(
            name='accommodationoperatorbinding',
            unique_together={('accommodation', 'tour_operator')},
        ),
    ]
