# Generated by Django 4.2.8 on 2026-02-25 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0009_rentalhub_hero_media_gallery_media_ids'),
        ('whatsapp', '0017_car_rental_whatsapp_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cargroupbinding',
            new_name='whatsapp_ca_car_id_05884a_idx',
            old_name='whatsapp_car_car_is_act_ix',
        ),
        migrations.RenameIndex(
            model_name='cargroupbinding',
            new_name='whatsapp_ca_whatsap_e4ca48_idx',
            old_name='whatsapp_car_group_is_act_ix',
        ),
        migrations.AlterField(
            model_name='whatsappreservationcode',
            name='accommodation',
            field=models.ForeignKey(blank=True, help_text='Accommodation for accommodation codes. Null when experience/car is set.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_reservation_codes', to='accommodations.accommodation', verbose_name='Accommodation'),
        ),
    ]
