# Generated by Django 4.2.8 on 2026-03-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0019_group_outreach_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupoutreachsent',
            new_name='whatsapp_gr_config__7d5a88_idx',
            old_name='whatsapp_gr_config__b0b0b0_idx',
        ),
        migrations.AlterField(
            model_name='groupoutreachconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='groupoutreachconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='groupoutreachsent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='groupoutreachsent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
