# Generated by Django 4.2.8 on 2026-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0023_whatsappreservationmessageconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappreservationmessageconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='whatsappreservationmessageconfig',
            name='templates',
            field=models.JSONField(blank=True, default=dict, help_text='Dict message_type -> template text, e.g. {"reservation_request": "Nueva solicitud...", "customer_waiting": "Estimado/a {{nombre_cliente}}..."}. Use {{variable}} for placeholders.', verbose_name='templates'),
        ),
    ]
