# Generated by Django 4.2.8 on 2025-11-14 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0037_add_ticket_tier_availability_fields'),
        ('organizers', '0012_add_service_fee_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('question_text', models.CharField(max_length=500, verbose_name='question text')),
                ('question_type', models.CharField(choices=[('rating', 'Rating (Stars)'), ('rating_10', 'Rating (1-10)'), ('rating_5', 'Rating (1-5)'), ('text', 'Text (Free)'), ('textarea', 'Long Text'), ('multiple_choice', 'Multiple Choice'), ('yes_no', 'Yes/No')], max_length=20, verbose_name='question type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('help_text', models.TextField(blank=True, verbose_name='help text')),
                ('min_rating', models.IntegerField(default=1, help_text='Valor mínimo para ratings', verbose_name='min rating')),
                ('max_rating', models.IntegerField(default=5, help_text='Valor máximo para ratings', verbose_name='max rating')),
            ],
            options={
                'verbose_name': 'satisfaction question',
                'verbose_name_plural': 'satisfaction questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20, verbose_name='status')),
                ('is_template', models.BooleanField(default=False, help_text='Si es una plantilla reutilizable', verbose_name='is template')),
                ('opens_at', models.DateTimeField(blank=True, help_text='Fecha de apertura del formulario', null=True, verbose_name='opens at')),
                ('closes_at', models.DateTimeField(blank=True, help_text='Fecha de cierre del formulario', null=True, verbose_name='closes at')),
                ('allow_multiple_responses', models.BooleanField(default=False, help_text='Permitir múltiples respuestas del mismo usuario', verbose_name='allow multiple responses')),
                ('require_email', models.BooleanField(default=False, help_text='Requerir email para responder', verbose_name='require email')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_satisfaction_surveys', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfaction_surveys', to='events.event', verbose_name='event')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfaction_surveys', to='organizers.organizer', verbose_name='organizer')),
            ],
            options={
                'verbose_name': 'satisfaction survey',
                'verbose_name_plural': 'satisfaction surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='satisfaction.satisfactionsurvey', verbose_name='survey')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfaction_responses', to='events.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'satisfaction response',
                'verbose_name_plural': 'satisfaction responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, verbose_name='option text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='satisfaction.satisfactionquestion', verbose_name='question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='satisfactionquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='satisfaction.satisfactionsurvey', verbose_name='survey'),
        ),
        migrations.CreateModel(
            name='SatisfactionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.IntegerField(blank=True, null=True, verbose_name='numeric value')),
                ('text_value', models.TextField(blank=True, verbose_name='text value')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='satisfaction.satisfactionquestionoption', verbose_name='selected option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='satisfaction.satisfactionquestion', verbose_name='question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='satisfaction.satisfactionresponse', verbose_name='response')),
            ],
            options={
                'verbose_name': 'satisfaction answer',
                'verbose_name_plural': 'satisfaction answers',
            },
        ),
        migrations.AddIndex(
            model_name='satisfactionsurvey',
            index=models.Index(fields=['slug'], name='satisfactio_slug_9fb848_idx'),
        ),
        migrations.AddIndex(
            model_name='satisfactionsurvey',
            index=models.Index(fields=['status'], name='satisfactio_status_2a27da_idx'),
        ),
        migrations.AddIndex(
            model_name='satisfactionsurvey',
            index=models.Index(fields=['event'], name='satisfactio_event_i_7bbc26_idx'),
        ),
        migrations.AddIndex(
            model_name='satisfactionresponse',
            index=models.Index(fields=['survey', '-submitted_at'], name='satisfactio_survey__9b0538_idx'),
        ),
        migrations.AddIndex(
            model_name='satisfactionresponse',
            index=models.Index(fields=['email'], name='satisfactio_email_b17928_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='satisfactionanswer',
            unique_together={('response', 'question')},
        ),
    ]
