# Generated by Django 4.2.8 on 2025-11-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionanswer',
            name='text_value',
            field=models.TextField(blank=True, null=True, verbose_name='text value'),
        ),
    ]
