# Generated by Django 4.2.8 on 2025-11-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0002_alter_satisfactionanswer_text_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
