# Generated by Django 4.2.8 on 2025-11-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0003_alter_satisfactionsurvey_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionresponse',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
