# Generated by Django 4.2.8 on 2026-02-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_destinations', '0002_media_and_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingdestination',
            name='images',
            field=models.JSONField(default=list, help_text='List of image URLs when not using gallery_media_ids', verbose_name='gallery image URLs fallback'),
        ),
        migrations.AlterField(
            model_name='landingdestination',
            name='local_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='local time (cached)'),
        ),
        migrations.AlterField(
            model_name='landingdestination',
            name='temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='temperature (cached)'),
        ),
    ]
