# Generated by Django 4.2.8 on 2025-05-01 01:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='onboarding completed'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='organization_size',
            field=models.CharField(blank=True, choices=[('small', 'Small (1-10 employees)'), ('medium', 'Medium (11-50 employees)'), ('large', 'Large (51+ employees)')], max_length=20, verbose_name='organization size'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='OrganizerOnboarding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_frequency', models.CharField(choices=[('occasional', 'Occasional (few times a year)'), ('regular', 'Regular (monthly)'), ('frequent', 'Frequent (weekly or more)')], max_length=20, verbose_name='event frequency')),
                ('expected_attendance', models.CharField(choices=[('small', 'Small (up to 50 people)'), ('medium', 'Medium (51-200 people)'), ('large', 'Large (201-1000 people)'), ('massive', 'Massive (1000+ people)')], max_length=20, verbose_name='expected attendance')),
                ('needs_ticketing', models.BooleanField(default=True, verbose_name='needs ticketing')),
                ('needs_accommodation', models.BooleanField(default=False, verbose_name='needs accommodation')),
                ('needs_experiences', models.BooleanField(default=False, verbose_name='needs experiences')),
                ('previous_platform', models.CharField(blank=True, max_length=255, verbose_name='previous platform')),
                ('main_goals', models.TextField(blank=True, verbose_name='main goals')),
                ('additional_requirements', models.TextField(blank=True, verbose_name='additional requirements')),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='organizers.organizer')),
            ],
            options={
                'verbose_name': 'organizer onboarding',
                'verbose_name_plural': 'organizer onboardings',
            },
        ),
    ]
