# Generated by Django 4.2.8 on 2025-05-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_organizer_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='event_frequency',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='expected_attendance',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='needs_accommodation',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='needs_experiences',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='needs_ticketing',
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='contact name'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='event_size',
            field=models.CharField(blank=True, choices=[('small', 'Small (up to 50 people)'), ('medium', 'Medium (51-200 people)'), ('large', 'Large (201-1000 people)'), ('massive', 'Massive (1000+ people)')], max_length=20, verbose_name='event size'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('none', 'No experience'), ('beginner', 'Less than 1 year'), ('intermediate', '1-3 years'), ('expert', 'More than 3 years')], max_length=20, verbose_name='experience level'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='has_experience',
            field=models.BooleanField(default=False, verbose_name='has previous experience'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='organization name'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='wants_accommodations',
            field=models.BooleanField(default=False, verbose_name='wants accommodations module'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='wants_events',
            field=models.BooleanField(default=False, verbose_name='wants events module'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='wants_experiences',
            field=models.BooleanField(default=False, verbose_name='wants experiences module'),
        ),
    ]
