# Generated by Django 4.2.8 on 2025-05-01 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0004_remove_organizeronboarding_event_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizeronboarding',
            name='accommodation_capacity',
            field=models.CharField(blank=True, choices=[('small', 'Small (1-10 rooms/units)'), ('medium', 'Medium (11-50 rooms/units)'), ('large', 'Large (50+ rooms/units)')], max_length=20, verbose_name='accommodation capacity'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('hotel', 'Hotel or inn'), ('apartment', 'Apartments or houses'), ('cabins', 'Cabins or glamping')], max_length=20, verbose_name='accommodation type'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='experience_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly or less')], max_length=20, verbose_name='experience frequency'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='experience_type',
            field=models.CharField(blank=True, choices=[('tours', 'Tours and guided visits'), ('workshops', 'Workshops and classes'), ('activities', 'Recreational activities')], max_length=20, verbose_name='experience type'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='experience_years',
            field=models.CharField(blank=True, choices=[('0-1', 'Less than 1 year'), ('1-3', '1-3 years'), ('3+', 'More than 3 years')], max_length=20, verbose_name='years of experience'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='onboarding_step',
            field=models.CharField(choices=[('modules', 'Modules selection'), ('organization', 'Organization details'), ('representative', 'Representative info'), ('complete', 'Completed')], default='modules', max_length=20, verbose_name='onboarding step'),
        ),
        migrations.CreateModel(
            name='OrganizerBilling',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_type', models.CharField(choices=[('natural', 'Natural Person'), ('juridica', 'Legal Entity')], default='natural', max_length=20, verbose_name='person type')),
                ('tax_name', models.CharField(max_length=255, verbose_name='tax name')),
                ('tax_id', models.CharField(max_length=30, verbose_name='tax ID')),
                ('billing_address', models.CharField(max_length=255, verbose_name='billing address')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt')], default='invoice', max_length=20, verbose_name='document type')),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='organizers.organizer')),
            ],
            options={
                'verbose_name': 'organizer billing',
                'verbose_name_plural': 'organizer billings',
            },
        ),
        migrations.CreateModel(
            name='OrganizerBanking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255, verbose_name='bank name')),
                ('account_type', models.CharField(max_length=50, verbose_name='account type')),
                ('account_number', models.CharField(max_length=50, verbose_name='account number')),
                ('account_holder', models.CharField(max_length=255, verbose_name='account holder')),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking', to='organizers.organizer')),
            ],
            options={
                'verbose_name': 'organizer banking',
                'verbose_name_plural': 'organizer banking',
            },
        ),
    ]
