# Generated by Django 4.2.8 on 2025-05-01 19:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0005_organizeronboarding_accommodation_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100, verbose_name='bank name')),
                ('account_type', models.CharField(max_length=50, verbose_name='account type')),
                ('account_number', models.CharField(max_length=50, verbose_name='account number')),
                ('account_holder', models.CharField(max_length=255, verbose_name='account holder')),
            ],
            options={
                'verbose_name': 'banking details',
                'verbose_name_plural': 'banking details',
            },
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_type', models.CharField(choices=[('natural', 'Natural Person'), ('juridica', 'Legal Entity')], default='natural', max_length=10, verbose_name='person type')),
                ('tax_name', models.CharField(max_length=255, verbose_name='tax name')),
                ('tax_id', models.CharField(max_length=20, verbose_name='tax ID')),
                ('billing_address', models.CharField(max_length=255, verbose_name='billing address')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt')], default='invoice', max_length=10, verbose_name='document type')),
            ],
            options={
                'verbose_name': 'billing details',
                'verbose_name_plural': 'billing details',
            },
        ),
        migrations.RemoveField(
            model_name='organizerbilling',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='additional_requirements',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='main_goals',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='onboarding_step',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='previous_platform',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='wants_accommodations',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='wants_events',
        ),
        migrations.RemoveField(
            model_name='organizeronboarding',
            name='wants_experiences',
        ),
        migrations.AddField(
            model_name='organizer',
            name='representative_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='representative email'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='representative_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='representative name'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='representative_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='representative phone'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='completed_step',
            field=models.IntegerField(default=0, verbose_name='completed step'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='contact email'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='contact phone'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='is completed'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='organization_size',
            field=models.CharField(blank=True, choices=[('small', 'Small (1-10 employees)'), ('medium', 'Medium (11-50 employees)'), ('large', 'Large (51+ employees)')], max_length=20, verbose_name='organization size'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='organization_slug',
            field=models.CharField(blank=True, max_length=255, verbose_name='organization slug'),
        ),
        migrations.AddField(
            model_name='organizeronboarding',
            name='selected_types',
            field=models.JSONField(default=list, verbose_name='selected modules'),
        ),
        migrations.AlterField(
            model_name='organizeronboarding',
            name='accommodation_capacity',
            field=models.CharField(blank=True, choices=[('small', 'Small (1-10 rooms/units)'), ('medium', 'Medium (11-50 rooms/units)'), ('large', 'Large (more than 50 rooms/units)')], max_length=10, verbose_name='accommodation capacity'),
        ),
        migrations.AlterField(
            model_name='organizeronboarding',
            name='event_size',
            field=models.CharField(blank=True, choices=[('small', 'Small (less than 100 people)'), ('medium', 'Medium (100-500 people)'), ('large', 'Large (more than 500 people)')], max_length=10, verbose_name='event size'),
        ),
        migrations.AlterField(
            model_name='organizeronboarding',
            name='experience_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly or less')], max_length=10, verbose_name='experience frequency'),
        ),
        migrations.AlterField(
            model_name='organizeronboarding',
            name='experience_years',
            field=models.CharField(blank=True, choices=[('0-1', 'Less than 1 year'), ('1-3', '1-3 years'), ('3+', 'More than 3 years')], max_length=5, verbose_name='experience years'),
        ),
        migrations.AlterField(
            model_name='organizeronboarding',
            name='has_experience',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, verbose_name='has previous experience'),
        ),
        migrations.DeleteModel(
            name='OrganizerBanking',
        ),
        migrations.DeleteModel(
            name='OrganizerBilling',
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='organizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_details', to='organizers.organizer'),
        ),
        migrations.AddField(
            model_name='bankingdetails',
            name='organizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking_details', to='organizers.organizer'),
        ),
    ]
