# Generated by Django 4.2.8 on 2025-06-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0006_bankingdetails_billingdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='organizer_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
