# Generated by Django 4.2.8 on 2025-06-22 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0007_remove_organizer_schema_name_organizer_organizer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizeronboarding',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='session key'),
        ),
        migrations.AlterField(
            model_name='organizeronboarding',
            name='organizer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding', to='organizers.organizer'),
        ),
    ]
