# Generated by Django 4.2.8 on 2025-06-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0008_organizeronboarding_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='organizer_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
