# Generated by Django 4.2.8 on 2025-11-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0012_add_service_fee_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='experience_dashboard_template',
            field=models.CharField(choices=[('standard', 'Standard'), ('free_tours', 'Free Tours')], default='standard', help_text='Template to use for experience dashboard (only applies if has_experience_module=True)', max_length=20, verbose_name='experience dashboard template'),
        ),
    ]
