# Generated by Django 4.2.8 on 2025-12-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0013_organizer_experience_dashboard_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='experience_dashboard_template',
            field=models.CharField(choices=[('v0', 'V0 (Legacy)'), ('principal', 'Principal')], default='principal', help_text='Template to use for experience dashboard (only applies if has_experience_module=True)', max_length=20, verbose_name='experience dashboard template'),
        ),
    ]
