# Generated by Django 4.2.8 on 2026-01-08 11:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0014_alter_organizer_experience_dashboard_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='is_student_center',
            field=models.BooleanField(default=False, help_text='Whether this organizer is a student center (Centro de Alumnos)', verbose_name='is student center'),
        ),
        migrations.CreateModel(
            name='StudentCenterConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for the slider/hero section', null=True, upload_to='student_centers/banners', verbose_name='banner image')),
                ('banner_text', models.TextField(blank=True, help_text='Custom text for the banner/slider section', verbose_name='banner text')),
                ('is_active', models.BooleanField(default=False, help_text='Whether the student center page is active and visible publicly', verbose_name='is active')),
                ('organizer', models.OneToOneField(help_text='The organizer (student center) this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='student_center_config', to='organizers.organizer', verbose_name='organizer')),
            ],
            options={
                'verbose_name': 'student center config',
                'verbose_name_plural': 'student center configs',
            },
        ),
    ]
