# Generated by Django 4.2.8 on 2026-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0015_organizer_is_student_center_studentcenterconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcenterconfig',
            name='banner_image_url',
            field=models.URLField(blank=True, help_text='Banner image URL from media library', max_length=500, null=True, verbose_name='banner image URL'),
        ),
        migrations.AlterField(
            model_name='studentcenterconfig',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for the slider/hero section (uploaded file)', null=True, upload_to='student_centers/banners', verbose_name='banner image'),
        ),
    ]
