# Generated by Django 4.2.8 on 2026-01-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0016_studentcenterconfig_banner_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcenterconfig',
            name='selected_experiences',
            field=models.JSONField(blank=True, default=list, help_text='List of experience IDs that the student center wants to display on their public page', verbose_name='selected experiences'),
        ),
    ]
