# Generated by Django 4.2.8 on 2025-11-17 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0013_organizer_experience_dashboard_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0037_add_ticket_tier_availability_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='short description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20, verbose_name='status')),
                ('type', models.CharField(choices=[('activity', 'Activity'), ('tour', 'Tour'), ('workshop', 'Workshop'), ('adventure', 'Adventure'), ('other', 'Other')], default='activity', max_length=20, verbose_name='type')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('is_free_tour', models.BooleanField(default=False, help_text="Whether this is a free tour (users don't pay, organizer pays credit per person)", verbose_name='is free tour')),
                ('credit_per_person', models.DecimalField(decimal_places=2, default=0, help_text='Cost to organizer per registered person (only for free tours)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='credit per person')),
                ('sales_cutoff_hours', models.IntegerField(default=2, help_text='Hours before tour start time to stop accepting bookings (1-2 hours)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='sales cutoff hours')),
                ('recurrence_pattern', models.JSONField(blank=True, default=dict, help_text='Weekly/daily recurrence configuration for tours', verbose_name='recurrence pattern')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='location name')),
                ('location_address', models.TextField(blank=True, verbose_name='location address')),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='location latitude')),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='location longitude')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration in minutes')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants (null = unlimited)', null=True, verbose_name='max participants')),
                ('min_participants', models.PositiveIntegerField(default=1, verbose_name='min participants')),
                ('included', models.JSONField(blank=True, default=list, help_text="List of what's included in the experience", verbose_name='included')),
                ('not_included', models.JSONField(blank=True, default=list, help_text="List of what's not included", verbose_name='not included')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='List of requirements for participants', verbose_name='requirements')),
                ('itinerary', models.JSONField(blank=True, default=list, help_text='List of itinerary items with time, title, description', verbose_name='itinerary')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs', verbose_name='images')),
                ('categories', models.JSONField(blank=True, default=list, verbose_name='categories')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='tags')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views count')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='organizers.organizer', verbose_name='organizer')),
            ],
            options={
                'verbose_name': 'experience',
                'verbose_name_plural': 'experiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='end datetime')),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=2, verbose_name='language')),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='status')),
                ('max_capacity', models.PositiveIntegerField(blank=True, help_text='Maximum capacity for this instance (null = uses experience default)', null=True, verbose_name='max capacity')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='experiences.experience', verbose_name='experience')),
            ],
            options={
                'verbose_name': 'tour instance',
                'verbose_name_plural': 'tour instances',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('participants_count', models.PositiveIntegerField(default=1, verbose_name='participants count')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_bookings', to='events.order', verbose_name='order')),
                ('tour_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='experiences.tourinstance', verbose_name='tour instance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_bookings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'tour booking',
                'verbose_name_plural': 'tour bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizerCredit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Credit amount charged (credit_per_person * participants_count)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('is_billed', models.BooleanField(default=False, help_text='Whether this credit has been billed to the organizer', verbose_name='is billed')),
                ('billed_at', models.DateTimeField(blank=True, null=True, verbose_name='billed at')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='organizers.organizer', verbose_name='organizer')),
                ('tour_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='experiences.tourbooking', verbose_name='tour booking')),
            ],
            options={
                'verbose_name': 'organizer credit',
                'verbose_name_plural': 'organizer credits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourLanguage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], max_length=2, verbose_name='language code')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='short description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this language version is active (can be blocked)', verbose_name='is active')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='experiences.experience', verbose_name='experience')),
            ],
            options={
                'verbose_name': 'tour language',
                'verbose_name_plural': 'tour languages',
                'indexes': [models.Index(fields=['experience', 'language_code'], name='experiences_experie_c7b272_idx'), models.Index(fields=['is_active'], name='experiences_is_acti_8f8979_idx')],
                'unique_together': {('experience', 'language_code')},
            },
        ),
        migrations.AddIndex(
            model_name='tourinstance',
            index=models.Index(fields=['experience', 'start_datetime'], name='experiences_experie_7f9fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='tourinstance',
            index=models.Index(fields=['status', 'start_datetime'], name='experiences_status_2f6a10_idx'),
        ),
        migrations.AddIndex(
            model_name='tourinstance',
            index=models.Index(fields=['language', 'status'], name='experiences_languag_54f972_idx'),
        ),
        migrations.AddIndex(
            model_name='tourbooking',
            index=models.Index(fields=['tour_instance', 'status'], name='experiences_tour_in_bca34d_idx'),
        ),
        migrations.AddIndex(
            model_name='tourbooking',
            index=models.Index(fields=['email'], name='experiences_email_679532_idx'),
        ),
        migrations.AddIndex(
            model_name='tourbooking',
            index=models.Index(fields=['user'], name='experiences_user_id_fc75e1_idx'),
        ),
        migrations.AddIndex(
            model_name='organizercredit',
            index=models.Index(fields=['organizer', 'is_billed'], name='experiences_organiz_d0fc91_idx'),
        ),
        migrations.AddIndex(
            model_name='organizercredit',
            index=models.Index(fields=['tour_booking'], name='experiences_tour_bo_783ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['organizer', 'status'], name='experiences_organiz_bbce91_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['is_free_tour', 'status'], name='experiences_is_free_80e8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['slug'], name='experiences_slug_bf245c_idx'),
        ),
    ]
