# Generated by Django 4.2.8 on 2025-12-23 14:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='booking_horizon_days',
            field=models.PositiveIntegerField(default=90, help_text='How many days into the future customers can book (instances are materialized within this window)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='booking horizon (days)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='capacity_count_rule',
            field=models.CharField(choices=[('all', 'All (adults + children + infants)'), ('exclude_infants', 'Adults + children only'), ('adults_only', 'Adults only')], default='all', help_text='Which participant types count toward capacity limits', max_length=20, verbose_name='capacity count rule'),
        ),
        migrations.AddField(
            model_name='experience',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price for children (only if is_child_priced=True)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='child price'),
        ),
        migrations.AddField(
            model_name='experience',
            name='currency',
            field=models.CharField(default='CLP', help_text='Currency code (ISO 4217)', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='experience',
            name='infant_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price for infants (only if is_infant_priced=True)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='infant price'),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_child_priced',
            field=models.BooleanField(default=False, help_text='Whether children are charged (if False, child_price is ignored)', verbose_name='charge for children'),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_infant_priced',
            field=models.BooleanField(default=False, help_text='Whether infants are charged (if False, infant_price is ignored)', verbose_name='charge for infants'),
        ),
        migrations.AddField(
            model_name='experience',
            name='pricing_mode',
            field=models.CharField(choices=[('per_person', 'Per Person'), ('per_booking', 'Per Booking')], default='per_person', help_text='Whether pricing is per person or per booking/group', max_length=20, verbose_name='pricing mode'),
        ),
        migrations.AddField(
            model_name='tourinstance',
            name='override_adult_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override adult price for this instance (null = use experience base)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='override adult price'),
        ),
        migrations.AddField(
            model_name='tourinstance',
            name='override_child_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override child price for this instance', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='override child price'),
        ),
        migrations.AddField(
            model_name='tourinstance',
            name='override_infant_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override infant price for this instance', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='override infant price'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price for adults (or per booking if pricing_mode=per_booking)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='base price (adult)'),
        ),
        migrations.CreateModel(
            name='ExperienceResource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('resource_type', models.CharField(choices=[('base', 'Base (always included)'), ('required_exclusive', 'Required (choose one)'), ('required_multiple', 'Required (choose quantity)'), ('optional', 'Optional add-on')], default='optional', max_length=20, verbose_name='resource type')),
                ('group_id', models.CharField(blank=True, help_text="Group identifier for related resources (e.g., 'kayak_type')", max_length=100, verbose_name='group ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Additional price for this resource', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('is_per_person', models.BooleanField(default=False, help_text='Whether price is multiplied by number of people using it', verbose_name='is per person')),
                ('people_per_unit', models.PositiveIntegerField(default=1, help_text='How many people can use one unit (e.g., 2 for tandem kayak)', verbose_name='people per unit')),
                ('available_quantity', models.PositiveIntegerField(blank=True, help_text='Total units available (null = unlimited)', null=True, verbose_name='available quantity')),
                ('image_url', models.URLField(blank=True, verbose_name='image URL')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='experiences.experience', verbose_name='experience')),
            ],
            options={
                'verbose_name': 'experience resource',
                'verbose_name_plural': 'experience resources',
                'ordering': ['experience', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='reservation ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('adult_count', models.PositiveIntegerField(default=1, verbose_name='adult count')),
                ('child_count', models.PositiveIntegerField(default=0, verbose_name='child count')),
                ('infant_count', models.PositiveIntegerField(default=0, verbose_name='infant count')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal')),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='service fee')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('currency', models.CharField(default='CLP', max_length=3, verbose_name='currency')),
                ('pricing_details', models.JSONField(blank=True, default=dict, help_text='Snapshot of pricing calculation (adult_price, child_price, resources, etc.)', verbose_name='pricing details')),
                ('selected_resources', models.JSONField(blank=True, default=list, help_text='List of {resource_id, resource_name, quantity, price}', verbose_name='selected resources')),
                ('capacity_count_rule', models.CharField(default='all', max_length=20, verbose_name='capacity count rule')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this reservation expires if not paid (null = no expiry)', null=True, verbose_name='expires at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='experiences.experience', verbose_name='experience')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='experiences.tourinstance', verbose_name='tour instance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_reservations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'experience reservation',
                'verbose_name_plural': 'experience reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceDatePriceOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('override_adult_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='override adult price')),
                ('override_child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='override child price')),
                ('override_infant_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='override infant price')),
                ('override_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='override capacity')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_price_overrides', to='experiences.experience', verbose_name='experience')),
            ],
            options={
                'verbose_name': 'experience date price override',
                'verbose_name_plural': 'experience date price overrides',
                'ordering': ['experience', 'date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceCapacityHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capacity_units', models.PositiveIntegerField(help_text='Number of capacity units held (calculated from participants + rule)', verbose_name='capacity units')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('released', models.BooleanField(default=False, help_text='Whether this hold has been released (expired or cancelled)', verbose_name='released')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='released at')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_holds', to='experiences.tourinstance', verbose_name='tour instance')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_holds', to='experiences.experiencereservation', verbose_name='reservation')),
            ],
            options={
                'verbose_name': 'experience capacity hold',
                'verbose_name_plural': 'experience capacity holds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceResourceHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units held', verbose_name='quantity')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('released', models.BooleanField(default=False, verbose_name='released')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='released at')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_holds', to='experiences.tourinstance', verbose_name='tour instance')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_holds', to='experiences.experiencereservation', verbose_name='reservation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='experiences.experienceresource', verbose_name='resource')),
            ],
            options={
                'verbose_name': 'experience resource hold',
                'verbose_name_plural': 'experience resource holds',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource', 'instance', 'released', 'expires_at'], name='experiences_resourc_326e6f_idx'), models.Index(fields=['reservation'], name='experiences_reserva_880573_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='experienceresource',
            index=models.Index(fields=['experience', 'is_active'], name='experiences_experie_a94aed_idx'),
        ),
        migrations.AddIndex(
            model_name='experienceresource',
            index=models.Index(fields=['group_id'], name='experiences_group_i_9d0f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencereservation',
            index=models.Index(fields=['reservation_id'], name='experiences_reserva_d3964a_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencereservation',
            index=models.Index(fields=['experience', 'status'], name='experiences_experie_f87ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencereservation',
            index=models.Index(fields=['instance', 'status'], name='experiences_instanc_0b9aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencereservation',
            index=models.Index(fields=['email'], name='experiences_email_ecd47b_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencereservation',
            index=models.Index(fields=['user'], name='experiences_user_id_c5a85a_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencereservation',
            index=models.Index(fields=['status', 'expires_at'], name='experiences_status_44ae02_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencedatepriceoverride',
            index=models.Index(fields=['experience', 'date'], name='experiences_experie_1416c5_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencecapacityhold',
            index=models.Index(fields=['instance', 'released', 'expires_at'], name='experiences_instanc_11926a_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencecapacityhold',
            index=models.Index(fields=['reservation'], name='experiences_reserva_0695d0_idx'),
        ),
    ]
