# Generated by Django 4.2.8 on 2025-12-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_add_flow_to_experience_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this experience was soft-deleted (null if not deleted)', null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this experience is active (visible publicly)', verbose_name='is active'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['is_active', 'deleted_at'], name='experiences_is_acti_911039_idx'),
        ),
    ]
