# Generated by Django 4.2.8 on 2025-12-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_add_soft_delete_and_active_to_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_whatsapp_reservation',
            field=models.BooleanField(default=False, help_text='If true, users reserve via WhatsApp to Tuki (+56947884342) instead of paying in platform', verbose_name='is whatsapp reservation'),
        ),
    ]
