# Generated by Django 4.2.8 on 2025-12-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0006_add_whatsapp_reservation_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='country',
            field=models.CharField(blank=True, help_text="Country assigned by SuperAdmin for categorization (e.g., 'Chile', 'Brasil', 'Colombia')", max_length=100, null=True, verbose_name='country'),
        ),
    ]
