# Generated by Django 4.2.8 on 2025-12-29 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_country_model'),
        ('experiences', '0007_add_country_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country assigned by SuperAdmin for categorization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='core.country', verbose_name='country'),
        ),
    ]
