# Generated by Django 4.2.8 on 2026-01-08 11:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0015_organizer_is_student_center_studentcenterconfig'),
        ('experiences', '0008_change_country_to_foreignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCenterTimelineItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Custom scheduled date for this experience', null=True, verbose_name='scheduled date')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Custom duration (overrides experience default if set)', null=True, verbose_name='duration in minutes')),
                ('min_participants', models.PositiveIntegerField(blank=True, help_text='Custom minimum participants (overrides experience default if set)', null=True, verbose_name='min participants')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Custom maximum participants (overrides experience default if set)', null=True, verbose_name='max participants')),
                ('interest_threshold', models.PositiveIntegerField(default=10, help_text='Minimum number of interested students required to confirm this experience', verbose_name='interest threshold')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='tentative', help_text='Current status of this timeline item', max_length=20, verbose_name='status')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which this item appears in the timeline', verbose_name='display order')),
                ('experience', models.ForeignKey(help_text='The base experience from the platform', on_delete=django.db.models.deletion.CASCADE, related_name='student_center_timeline_items', to='experiences.experience', verbose_name='experience')),
                ('student_center', models.ForeignKey(help_text='The student center organizer this timeline item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='organizers.organizer', verbose_name='student center')),
            ],
            options={
                'verbose_name': 'student center timeline item',
                'verbose_name_plural': 'student center timeline items',
                'ordering': ['display_order', 'scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the interested student', max_length=255, verbose_name='name')),
                ('email', models.EmailField(help_text='Email address of the interested student', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Phone number of the interested student', max_length=30, verbose_name='phone')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('converted', 'Converted')], default='pending', help_text='Current status of this interest', max_length=20, verbose_name='status')),
                ('timeline_item', models.ForeignKey(help_text='The timeline item this interest is for', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='experiences.studentcentertimelineitem', verbose_name='timeline item')),
            ],
            options={
                'verbose_name': 'student interest',
                'verbose_name_plural': 'student interests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['timeline_item', 'status'], name='experiences_timelin_92e781_idx'), models.Index(fields=['email'], name='experiences_email_d44445_idx'), models.Index(fields=['status'], name='experiences_status_ad634e_idx')],
                'unique_together': {('timeline_item', 'email')},
            },
        ),
        migrations.AddIndex(
            model_name='studentcentertimelineitem',
            index=models.Index(fields=['student_center', 'status'], name='experiences_student_5cab04_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcentertimelineitem',
            index=models.Index(fields=['scheduled_date'], name='experiences_schedul_3f1194_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcentertimelineitem',
            index=models.Index(fields=['display_order'], name='experiences_display_c45d91_idx'),
        ),
    ]
