# Generated by Django 4.2.8 on 2026-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0017_experience_whatsapp_message_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='whatsapp_message_templates',
            field=models.JSONField(blank=True, default=dict, help_text='Optional overrides for reservation flow messages. Keys: reservation_request, customer_waiting, customer_confirmation, customer_rejection, payment_link, payment_confirmed, ticket_info, reminder, customer_availability_confirmed, customer_confirm_free. Empty = use platform/operator default.', verbose_name='WhatsApp message templates'),
        ),
    ]
