# Generated by Django 4.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0018_alter_experience_whatsapp_message_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='auto_approve_free_tour_reservations',
            field=models.BooleanField(
                default=False,
                help_text='If True, new free tour reservations are confirmed immediately and the customer receives the confirmation message without waiting for operator approval. Operator still receives the notification.',
                verbose_name='auto approve free tour reservations'
            ),
        ),
    ]
