# Generated by Django 4.2.8 on 2026-03-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0006_alter_travelguide_body'),
        ('experiences', '0019_experience_auto_approve_free_tour_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourinstance',
            name='is_publicly_listed',
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text='If False, the instance is only exposed through a specific travel guide flow.',
                verbose_name='is publicly listed',
            ),
        ),
        migrations.AddField(
            model_name='tourinstance',
            name='origin_block_key',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Stable block key inside the guide body that owns this custom instance.',
                max_length=64,
                verbose_name='origin block key',
            ),
        ),
        migrations.AddField(
            model_name='tourinstance',
            name='origin_travel_guide',
            field=models.ForeignKey(
                blank=True,
                help_text='Travel guide that created this hidden/custom instance.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='generated_experience_instances',
                to='travel_guides.travelguide',
                verbose_name='origin travel guide',
            ),
        ),
        migrations.AddField(
            model_name='experiencereservation',
            name='source_type',
            field=models.CharField(
                choices=[('direct', 'Direct'), ('travel_guide', 'Travel guide')],
                db_index=True,
                default='direct',
                help_text='Whether the reservation started directly on the experience or from a travel guide.',
                max_length=30,
                verbose_name='source type',
            ),
        ),
        migrations.AddField(
            model_name='experiencereservation',
            name='travel_guide',
            field=models.ForeignKey(
                blank=True,
                help_text='Travel guide that originated this reservation, when applicable.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='experience_reservations',
                to='travel_guides.travelguide',
                verbose_name='travel guide',
            ),
        ),
        migrations.AddField(
            model_name='experiencereservation',
            name='travel_guide_block_key',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Stable block key of the embed_experience block inside the travel guide.',
                max_length=64,
                verbose_name='travel guide block key',
            ),
        ),
        migrations.AddField(
            model_name='experiencereservation',
            name='travel_guide_context',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Snapshot of guide-specific booking context (guide title, slot label, campaign data, etc.).',
                verbose_name='travel guide context',
            ),
        ),
        migrations.AddIndex(
            model_name='tourinstance',
            index=models.Index(fields=['experience', 'is_publicly_listed', 'status'], name='exp_tinst_public_idx'),
        ),
        migrations.AddIndex(
            model_name='tourinstance',
            index=models.Index(fields=['origin_travel_guide', 'origin_block_key'], name='exp_tinst_origin_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencereservation',
            index=models.Index(fields=['source_type', 'travel_guide'], name='exp_res_source_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencereservation',
            index=models.Index(fields=['travel_guide_block_key'], name='exp_res_block_idx'),
        ),
    ]
