# Generated by Django 4.2.8 on 2026-03-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0020_travel_guide_booking_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='experiencereservation',
            new_name='experiences_source__aec541_idx',
            old_name='exp_res_source_idx',
        ),
        migrations.RenameIndex(
            model_name='experiencereservation',
            new_name='experiences_travel__f9c87f_idx',
            old_name='exp_res_block_idx',
        ),
        migrations.RenameIndex(
            model_name='tourinstance',
            new_name='experiences_experie_7f3616_idx',
            old_name='exp_tinst_public_idx',
        ),
        migrations.RenameIndex(
            model_name='tourinstance',
            new_name='experiences_origin__0715af_idx',
            old_name='exp_tinst_origin_idx',
        ),
    ]
