# Generated by Django 4.2.8 on 2026-03-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0022_creator_commission_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='creator_commission_basis',
            field=models.CharField(choices=[('pct_tuki_commission', 'Percentage of Tuki commission'), ('pct_total', 'Percentage of sale total')], default='pct_tuki_commission', help_text='Base for commission: pct_tuki_commission = %% of what Tuki charges; pct_total = %% of total sold.', max_length=30, verbose_name='creator commission basis'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='creator_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Creator share: if basis=pct_tuki_commission then % of platform fee (e.g. 0.5=50%%); if basis=pct_total then % of sale total (e.g. 0.06=6%%).', max_digits=5, null=True, verbose_name='creator commission rate'),
        ),
    ]
