# Generated by Django 4.2.8 on 2025-05-02 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the password was last changed.', verbose_name='last password change'),
        ),
    ]
