# Generated by Django 4.2.8 on 2025-06-22 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0007_remove_organizer_schema_name_organizer_organizer_id_and_more'),
        ('users', '0002_user_last_password_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='user',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizers.organizer', verbose_name='organizer'),
        ),
    ]
