# Generated by Django 4.2.8 on 2025-09-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_tenant_id_user_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text="User created automatically from purchase, hasn't completed profile.", verbose_name='guest status'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the user completed their profile.', null=True, verbose_name='profile completed at'),
        ),
    ]
