# Generated by hand for travel_guides app

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('template', models.CharField(choices=[('editorial', 'Editorial'), ('multi_day_itinerary', 'Multi-day itinerary'), ('best_activities', 'Best activities')], default='editorial', max_length=40, verbose_name='template')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(db_index=True, max_length=255, unique=True, verbose_name='slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='excerpt')),
                ('hero_media_id', models.UUIDField(blank=True, null=True, verbose_name='hero image from media library')),
                ('hero_image', models.URLField(blank=True, max_length=500, verbose_name='hero image URL fallback')),
                ('body', models.JSONField(blank=True, default=list, help_text='List of blocks: paragraph, heading, image, itinerary, embed_experience, embed_accommodation, embed_destination, embed_event, embed_experiences, blockquote', verbose_name='body')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('og_image', models.URLField(blank=True, max_length=500, verbose_name='og image URL')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_guides', to='landing_destinations.landingdestination', verbose_name='destination')),
            ],
            options={
                'verbose_name': 'Travel Guide',
                'verbose_name_plural': 'Travel Guides',
                'ordering': ['display_order', '-published_at', '-created_at'],
            },
        ),
    ]
