# Generated by Django 4.2.8 on 2026-03-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_destinations', '0004_car_rental_ids_and_featured_car_rental'),
        ('travel_guides', '0002_travelguide_preview_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelguide',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_entries', to='landing_destinations.landingdestination', verbose_name='destination'),
        ),
    ]
