# Generated by Django 4.2.8 on 2026-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0004_add_hero_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelguide',
            name='hero_slides',
            field=models.JSONField(blank=True, default=list, help_text='List of { "media_id": "uuid", "caption": "" } for hero slider. If non-empty, hero is shown as slider like Erasmus; else hero_media_id/hero_image used as single image.', verbose_name='hero slider slides'),
        ),
    ]
