# Generated by Django 4.2.8 on 2026-03-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0005_alter_travelguide_hero_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelguide',
            name='body',
            field=models.JSONField(blank=True, default=list, help_text='List of blocks: paragraph, heading, image, itinerary, embed_experience, embed_experiences, embed_accommodation, embed_destination, embed_event, embed_erasmus_activity, embed_erasmus_activities, blockquote, gallery, checklist', verbose_name='body'),
        ),
    ]
