# Generated by Django 4.2.8 on 2026-03-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0006_alter_travelguide_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelguide',
            name='body',
            field=models.JSONField(blank=True, default=list, help_text='List of blocks: paragraph, heading, image, itinerary, embed_experience, embed_experiences, embed_accommodation, embed_destination, embed_event, embed_erasmus_activity, embed_erasmus_activities, blockquote, gallery, checklist, countdown, cta_button', verbose_name='body'),
        ),
    ]
