# Generated by Django 4.2.8 on 2025-10-06 16:20

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_allow_null_available_in_ticket_tier'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(default=dict, help_text='Simple field responses')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.form')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_response', to='events.ticket')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='Allow multiple selections'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='allowed_file_types',
            field=models.TextField(blank=True, help_text="Comma-separated list of allowed file extensions (e.g., 'pdf,doc,docx')", null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='max_file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum file size in MB (for file/image fields)', null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='show_other_option',
            field=models.BooleanField(default=False, help_text="Show 'Other' option with text input"),
        ),
        migrations.AddField(
            model_name='formfield',
            name='step_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('date', 'Date'), ('textarea', 'Textarea'), ('heading', 'Heading'), ('paragraph', 'Paragraph'), ('file', 'File Upload'), ('image', 'Image Upload'), ('url', 'URL'), ('time', 'Time'), ('datetime', 'Date & Time'), ('rating', 'Rating (1-5)'), ('slider', 'Slider'), ('multi_select', 'Multiple Select'), ('signature', 'Digital Signature')], max_length=20),
        ),
        migrations.CreateModel(
            name='FormResponseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.utils.get_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formfield')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='forms.formresponse')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
