# Generated by Django 4.2.8 on 2025-09-01 05:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email al que se envía el código', max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'El código debe tener 6 dígitos')], verbose_name='Código OTP')),
                ('purpose', models.CharField(choices=[('event_creation', 'Creación de Evento'), ('login', 'Inicio de Sesión'), ('ticket_access', 'Acceso a Tickets'), ('password_reset', 'Recuperación de Contraseña'), ('email_verification', 'Verificación de Email'), ('account_creation', 'Creación de Cuenta')], help_text='Para qué se usa este código', max_length=20, verbose_name='Propósito')),
                ('is_used', models.BooleanField(default=False, help_text='Si el código ya fue utilizado', verbose_name='¿Usado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('expires_at', models.DateTimeField(help_text='Cuándo expira el código', verbose_name='Expira')),
                ('used_at', models.DateTimeField(blank=True, help_text='Cuándo se usó el código', null=True, verbose_name='Usado en')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de creación')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Número de intentos de validación', verbose_name='Intentos')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional contextual', verbose_name='Metadatos')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario asociado (si existe)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Código OTP',
                'verbose_name_plural': 'Códigos OTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_code', models.CharField(max_length=6, verbose_name='Código intentado')),
                ('is_successful', models.BooleanField(default=False, verbose_name='¿Exitoso?')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del intento')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent del intento')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Intentado en')),
                ('otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_attempts', to='otp.otp')),
            ],
            options={
                'verbose_name': 'Intento de OTP',
                'verbose_name_plural': 'Intentos de OTP',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'purpose', 'is_used'], name='otp_otp_email_335f46_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='otp_otp_expires_d5b803_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['created_at'], name='otp_otp_created_441207_idx'),
        ),
    ]
