# Generated by Django 4.2.8 on 2025-12-27 14:14

import apps.media.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0013_organizer_experience_dashboard_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('organizer', 'Organizer'), ('global', 'Global')], default='organizer', help_text='Asset scope: organizer-specific or global (site-wide)', max_length=20, verbose_name='scope')),
                ('file', models.ImageField(upload_to=apps.media.models.get_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('content_type', models.CharField(max_length=100, verbose_name='content type')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='size in bytes')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('sha256', models.CharField(blank=True, help_text='For deduplication', max_length=64, verbose_name='SHA256 hash')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('organizer', models.ForeignKey(blank=True, help_text='Owner organizer (required if scope=organizer)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='organizers.organizer', verbose_name='organizer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'media asset',
                'verbose_name_plural': 'media assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('field_name', models.CharField(help_text="Which field uses this asset (e.g., 'main_image', 'gallery')", max_length=100, verbose_name='field name')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='media.mediaasset', verbose_name='asset')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'media usage',
                'verbose_name_plural': 'media usages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='media_media_content_c4e0d1_idx'), models.Index(fields=['asset', '-created_at'], name='media_media_asset_i_39f6cc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['scope', 'organizer', '-created_at'], name='media_media_scope_9b4469_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['sha256'], name='media_media_sha256_93aeed_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['deleted_at'], name='media_media_deleted_09bfbc_idx'),
        ),
    ]
