# Generated by Django 4.2.8 on 2026-02-18 17:12

import apps.media.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_allow_avif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.ImageField(upload_to=apps.media.models.get_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='file'),
        ),
    ]
