# Generated by Django for apps.erasmus

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErasmusTrackingLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="e.g. Instagram María", max_length=255, verbose_name="name")),
                ("slug", models.SlugField(db_index=True, max_length=100, unique=True, verbose_name="slug")),
            ],
            options={
                "verbose_name": "Erasmus tracking link",
                "verbose_name_plural": "Erasmus tracking links",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ErasmusLead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("first_name", models.CharField(max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(max_length=150, verbose_name="last name")),
                ("nickname", models.CharField(blank=True, max_length=100, verbose_name="nickname")),
                ("birth_date", models.DateField(verbose_name="birth date")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="email")),
                ("phone_country_code", models.CharField(max_length=10, verbose_name="phone country code")),
                ("phone_number", models.CharField(max_length=20, verbose_name="phone number")),
                ("instagram", models.CharField(blank=True, max_length=100, verbose_name="instagram")),
                ("university", models.CharField(max_length=255, verbose_name="university")),
                ("degree", models.CharField(max_length=255, verbose_name="degree / career")),
                ("arrival_date", models.DateField(verbose_name="arrival date")),
                ("departure_date", models.DateField(verbose_name="departure date")),
                (
                    "destinations",
                    models.JSONField(
                        default=list,
                        help_text="List of destination/experience slugs selected",
                        verbose_name="destinations",
                    ),
                ),
                (
                    "interests",
                    models.JSONField(
                        default=list,
                        help_text="List of interest slugs/ids selected",
                        verbose_name="interests",
                    ),
                ),
                (
                    "source_slug",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Tracking link identifier (e.g. from ?source=maria_ig)",
                        max_length=100,
                        null=True,
                        verbose_name="source slug",
                    ),
                ),
                ("utm_source", models.CharField(blank=True, max_length=255, null=True, verbose_name="utm source")),
                ("utm_medium", models.CharField(blank=True, max_length=255, null=True, verbose_name="utm medium")),
                ("utm_campaign", models.CharField(blank=True, max_length=255, null=True, verbose_name="utm campaign")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="erasmus_leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Erasmus lead",
                "verbose_name_plural": "Erasmus leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
