# Generated by Django 4.2.8 on 2026-02-18 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erasmus', '0008_add_interested_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmuslead',
            name='completion_status',
            field=models.CharField(choices=[('complete', 'Completo'), ('pending_completion', 'Por completar')], db_index=True, default='complete', help_text='Por completar: lead cargado con datos parciales (ej. WhatsApp), falta completar en el formulario', max_length=30, verbose_name='completion status'),
        ),
        migrations.AlterField(
            model_name='erasmusdestinationguide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='erasmusdestinationguide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='erasmuslead',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='arrival date'),
        ),
        migrations.AlterField(
            model_name='erasmuslead',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='erasmuslead',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='departure date'),
        ),
        migrations.AlterField(
            model_name='erasmuslead',
            name='stay_reason',
            field=models.CharField(choices=[('university', 'Intercambio / Erasmus (universidad)'), ('practicas', 'Prácticas / Internship'), ('other', 'Otro')], help_text='Qué viene a hacer: universidad, prácticas u otro', max_length=20, verbose_name='reason for stay'),
        ),
        migrations.AlterField(
            model_name='erasmuslead',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked when account is created (e.g. from email)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasmus_leads', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
