# Generated by Django 4.2.8 on 2026-02-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erasmus', '0011_erasmustimelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmuslead',
            name='requested_whatsapp_approval_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Cuando el lead pulsó 'Confirmar que terminé mi registro' para que el operador lo apruebe en el grupo", null=True, verbose_name='requested WhatsApp approval at'),
        ),
    ]
