# Generated by Django 4.2.8 on 2026-02-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0015_add_experience_imported_review'),
        ('erasmus', '0014_add_erasmus_activity_and_instance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='erasmusactivity',
            new_name='erasmus_era_slug_8c9813_idx',
            old_name='erasmus_act_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='erasmusactivity',
            new_name='erasmus_era_is_acti_77bbcc_idx',
            old_name='erasmus_act_active_ord_idx',
        ),
        migrations.RenameIndex(
            model_name='erasmusactivityinstance',
            new_name='erasmus_era_activit_45a84b_idx',
            old_name='erasmus_inst_act_date_idx',
        ),
        migrations.RenameIndex(
            model_name='erasmusactivityinstance',
            new_name='erasmus_era_is_acti_4563da_idx',
            old_name='erasmus_inst_active_idx',
        ),
        migrations.AlterField(
            model_name='erasmusactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='erasmusactivity',
            name='experience',
            field=models.ForeignKey(blank=True, help_text='Optional link to a bookable experience', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasmus_activities', to='experiences.experience', verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='erasmusactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='erasmusactivityinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='erasmusactivityinstance',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Exact date when set; otherwise use month/year or labels', null=True, verbose_name='scheduled date'),
        ),
        migrations.AlterField(
            model_name='erasmusactivityinstance',
            name='scheduled_label_en',
            field=models.CharField(blank=True, help_text='e.g. March 2026', max_length=100, verbose_name='scheduled label English'),
        ),
        migrations.AlterField(
            model_name='erasmusactivityinstance',
            name='scheduled_label_es',
            field=models.CharField(blank=True, help_text='e.g. Marzo 2026', max_length=100, verbose_name='scheduled label Spanish'),
        ),
        migrations.AlterField(
            model_name='erasmusactivityinstance',
            name='scheduled_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-12 for month-only (e.g. March)', null=True, verbose_name='scheduled month'),
        ),
        migrations.AlterField(
            model_name='erasmusactivityinstance',
            name='scheduled_year',
            field=models.IntegerField(blank=True, help_text='Year for month-only scheduling', null=True, verbose_name='scheduled year'),
        ),
        migrations.AlterField(
            model_name='erasmusactivityinstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
