# Generated by Django 4.2.8 on 2026-02-19 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erasmus', '0019_add_alojamiento_ideal_extra_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasmusLocalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('role', models.CharField(blank=True, help_text="Title/role, e.g. 'Founder & Guide'", max_length=150, verbose_name='role')),
                ('photo', models.ImageField(blank=True, help_text='Profile photo for the community card', null=True, upload_to='erasmus_partners/%Y/%m/', verbose_name='photo')),
                ('bio', models.TextField(blank=True, help_text='Short description (1–2 lines)', verbose_name='bio')),
                ('instagram_username', models.CharField(blank=True, help_text='Username without @. Link will be instagram.com/{username}', max_length=100, verbose_name='instagram username')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Full number with country code, e.g. 56912345678. Link: wa.me/{number}', max_length=30, verbose_name='whatsapp number')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Erasmus local partner',
                'verbose_name_plural': 'Erasmus local partners',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ErasmusMagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('access_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='access token')),
                ('target', models.CharField(choices=[('community', 'Comunidad Erasmus'), ('whatsapp', 'Grupos de WhatsApp')], max_length=20, verbose_name='target')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('is_used', models.BooleanField(default=False, verbose_name='used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='erasmus.erasmuslead', verbose_name='Erasmus lead')),
            ],
            options={
                'verbose_name': 'Erasmus magic link',
                'verbose_name_plural': 'Erasmus magic links',
                'ordering': ['-created_at'],
            },
        ),
    ]
