# Generated by Django 4.2.8 on 2026-02-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erasmus', '0021_erasmusmagiclink_whatsapp_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmusmagiclink',
            name='verification_code',
            field=models.CharField(db_index=True, help_text='Code embedded in the WhatsApp pre-fill message (e.g. ERAS-A1B2C3)', max_length=30, unique=True, verbose_name='verification code'),
        ),
    ]
