# Generated by Django 4.2.8 on 2026-02-19 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_mediaasset_file'),
        ('erasmus', '0022_alter_erasmusmagiclink_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmuslocalpartner',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Profile photo from Biblioteca de Medios.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset', verbose_name='photo (from media library)'),
        ),
        migrations.AlterField(
            model_name='erasmuslocalpartner',
            name='photo',
            field=models.ImageField(blank=True, help_text='Legacy: direct upload. Prefer asset from media library.', null=True, upload_to='erasmus_partners/%Y/%m/', verbose_name='photo'),
        ),
    ]
