# Generated by Django 4.2.8 on 2026-02-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erasmus', '0028_erasmus_activity_experience_like_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmusactivity',
            name='location',
            field=models.CharField(blank=True, help_text='Short location label (e.g. city or area)', max_length=255, verbose_name='location'),
        ),
    ]
