# Generated by Django 4.2.8 on 2026-02-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erasmus', '0030_remove_alojamiento_ideal_extra_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasmuslead',
            name='budget_stay',
            field=models.CharField(blank=True, help_text='Presupuesto aproximado durante el intercambio (estancia, paseos, etc.)', max_length=200, verbose_name='budget during stay'),
        ),
        migrations.AddField(
            model_name='erasmuslead',
            name='budget_trip',
            field=models.CharField(blank=True, help_text='Presupuesto aproximado para el viaje (vuelos, llegada a Chile)', max_length=200, verbose_name='budget for trip'),
        ),
    ]
