# Generated by Django 4.2.8 on 2026-02-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erasmus', '0040_erasmusactivityreview_and_review_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='erasmusactivityreview',
            new_name='erasmus_era_instanc_c377d9_idx',
            old_name='erasmus_era_instance_7a0b0d_idx',
        ),
        migrations.AlterField(
            model_name='erasmusactivityreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='erasmusactivityreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
