# Generated by hand to fix conflicting migrations (two 0041 in erasmus)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erasmus", "0041_erasmusactivitypubliclink_review_link_enabled"),
        ("erasmus", "0041_rename_erasmus_era_instance_7a0b0d_idx_erasmus_era_instanc_c377d9_idx_and_more"),
    ]

    operations = []
