# Generated by Django 4.2.8 on 2026-03-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erasmus', '0044_erasmus_activity_paid_and_inscription_payment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='erasmusactivityinscriptionpayment',
            new_name='erasmus_era_instanc_6e4617_idx',
            old_name='erasmus_era_instance_8a1f0c_idx',
        ),
    ]
