# Generated by Django 4.2.8 on 2026-03-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erasmus', '0046_merge_0045_paymentlink_and_index_rename'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='erasmusactivitypaymentlink',
            new_name='erasmus_era_instanc_4f011d_idx',
            old_name='erasmus_era_instanc_idx',
        ),
        migrations.AlterField(
            model_name='erasmusactivityinscriptionpayment',
            name='payment_method',
            field=models.CharField(choices=[('platform', 'Pago en línea (plataforma)'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('mercadopago', 'Mercado Pago'), ('paypal', 'PayPal'), ('other', 'Otro')], default='efectivo', max_length=32, verbose_name='payment method'),
        ),
    ]
