# Generated by Django 4.2.8 on 2026-03-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erasmus', '0048_erasmuswelcomemessageconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmuswelcomemessageconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='erasmuswelcomemessageconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
