# Generated by Django 4.2.8 on 2026-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erasmus', '0053_activity_extra_fields_and_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasmusactivityinstanceregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='erasmusactivityinstanceregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
