# Generated by Django 4.2.8 on 2026-03-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erasmus', '0056_add_contest_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contestregistration',
            new_name='erasmus_con_contest_68a53a_idx',
            old_name='erasmus_con_contest_5a0f0d_idx',
        ),
    ]
