# Generated by Django 4.2.8 on 2026-02-25 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_platformuptimeheartbeat_id_and_more'),
        ('car_rental', '0001_initial_car_rental'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='car',
            new_name='car_rental__company_708be8_idx',
            old_name='car_rental_c_company_7a0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='car',
            new_name='car_rental__slug_a2e8cc_idx',
            old_name='car_rental_c_slug_8b2c4a_idx',
        ),
        migrations.RenameIndex(
            model_name='carblockeddate',
            new_name='car_rental__car_id_f8f34a_idx',
            old_name='car_rental_c_car_id_2a1b5c_idx',
        ),
        migrations.RenameIndex(
            model_name='carreservation',
            new_name='car_rental__reserva_df8ac9_idx',
            old_name='car_rental_c_reserva_3d4e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='carreservation',
            new_name='car_rental__car_id_d23a33_idx',
            old_name='car_rental_c_car_id_4e5f7a_idx',
        ),
        migrations.RenameIndex(
            model_name='carreservation',
            new_name='car_rental__pickup__3fdce7_idx',
            old_name='car_rental_c_pickup__5f6a8b_idx',
        ),
        migrations.AlterField(
            model_name='car',
            name='conditions_override',
            field=models.JSONField(blank=True, default=dict, help_text='Override or complement company conditions when not inheriting', verbose_name='conditions override'),
        ),
        migrations.AlterField(
            model_name='car',
            name='included',
            field=models.JSONField(blank=True, default=list, help_text="List of what's included", verbose_name='included'),
        ),
        migrations.AlterField(
            model_name='car',
            name='not_included',
            field=models.JSONField(blank=True, default=list, help_text="List of what's not included", verbose_name='not included'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pickup_time_default',
            field=models.CharField(blank=True, help_text='HH:MM', max_length=5, verbose_name='default pickup time'),
        ),
        migrations.AlterField(
            model_name='car',
            name='return_time_default',
            field=models.CharField(blank=True, help_text='HH:MM', max_length=5, verbose_name='default return time'),
        ),
        migrations.AlterField(
            model_name='carrentalcompany',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Common conditions: guarantee, insurance, damage_policy, min_age, etc.', verbose_name='conditions'),
        ),
        migrations.AlterField(
            model_name='carrentalcompany',
            name='gallery_media_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of MediaAsset UUIDs for the company gallery', verbose_name='gallery media asset IDs'),
        ),
        migrations.AlterField(
            model_name='carrentalcompany',
            name='hero_media_id',
            field=models.UUIDField(blank=True, help_text='MediaAsset UUID for hero image', null=True, verbose_name='hero image from media library'),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='flow',
            field=models.ForeignKey(blank=True, help_text='Platform flow tracking this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_rental_reservations', to='core.platformflow', verbose_name='platform flow'),
        ),
    ]
