# Generated by Django 4.2.8 on 2026-02-04 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('creators', '0001_creators_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLandingSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_key', models.CharField(help_text='e.g. creators_landing_hero, creators_landing_bento_1', max_length=100, unique=True, verbose_name='slot key')),
            ],
            options={
                'verbose_name': 'platform landing slot',
                'verbose_name_plural': 'platform landing slots',
                'ordering': ['slot_key'],
            },
        ),
        migrations.RenameIndex(
            model_name='creatorprofile',
            new_name='creators_cr_slug_d6b6b6_idx',
            old_name='creators_cr_slug_8b2b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='creatorprofile',
            new_name='creators_cr_is_appr_9cf2e3_idx',
            old_name='creators_cr_is_appr_2c8e0a_idx',
        ),
        migrations.RenameIndex(
            model_name='creatorrecommendedexperience',
            new_name='creators_cr_creator_5b1e65_idx',
            old_name='creators_cr_creator_9a1f2b_idx',
        ),
        migrations.AddField(
            model_name='platformlandingslot',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_slots', to='media.mediaasset', verbose_name='asset'),
        ),
    ]
