# Generated by Django 4.2.8 on 2026-02-04 16:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0010_add_creator_commission_fields'),
        ('creators', '0002_platform_landing_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(help_text='URL handle for this relato (unique per creator)', max_length=120, verbose_name='slug')),
                ('body', models.JSONField(blank=True, default=list, help_text='List of blocks: paragraph, heading, itinerary, image. Itinerary items: { time, title, description }', verbose_name='body')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to='creators.creatorprofile', verbose_name='creator')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatos', to='experiences.experience', verbose_name='linked experience')),
            ],
            options={
                'verbose_name': 'relato',
                'verbose_name_plural': 'relatos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['creator', 'status'], name='creators_re_creator_a1a78c_idx')],
                'unique_together': {('creator', 'slug')},
            },
        ),
    ]
