# Generated by Django 4.2.8 on 2026-02-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_relato_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='For work group and notifications (e.g. WhatsApp)', max_length=30, verbose_name='phone'),
        ),
    ]
