# Generated by Django 4.2.8 on 2026-03-03 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_add_creator_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroVitrinaItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('experience', 'Experiencia'), ('accommodation', 'Alojamiento'), ('event', 'Evento'), ('rent_a_car', 'Rent a car')], db_index=True, max_length=32, verbose_name='content type')),
                ('object_id', models.UUIDField(db_index=True, help_text='UUID of the experience, accommodation, event or car (Car model).', verbose_name='object id')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'hero vitrina item',
                'verbose_name_plural': 'hero vitrina items',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['order'], name='creators_he_order_97f874_idx')],
            },
        ),
    ]
